// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v5.29.3
// source: api/attendance-core/service/v1/attendance-core.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationAttendanceServiceGetMonthlyAttendance = "/attendancecore.v1.AttendanceService/GetMonthlyAttendance"

type AttendanceServiceHTTPServer interface {
	GetMonthlyAttendance(context.Context, *GetMonthlyAttendanceRequest) (*GetMonthlyAttendanceResponse, error)
}

func RegisterAttendanceServiceHTTPServer(s *http.Server, srv AttendanceServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/attendance", _AttendanceService_GetMonthlyAttendance0_HTTP_Handler(srv))
}

func _AttendanceService_GetMonthlyAttendance0_HTTP_Handler(srv AttendanceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetMonthlyAttendanceRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAttendanceServiceGetMonthlyAttendance)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetMonthlyAttendance(ctx, req.(*GetMonthlyAttendanceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetMonthlyAttendanceResponse)
		return ctx.Result(200, reply)
	}
}

type AttendanceServiceHTTPClient interface {
	GetMonthlyAttendance(ctx context.Context, req *GetMonthlyAttendanceRequest, opts ...http.CallOption) (rsp *GetMonthlyAttendanceResponse, err error)
}

type AttendanceServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewAttendanceServiceHTTPClient(client *http.Client) AttendanceServiceHTTPClient {
	return &AttendanceServiceHTTPClientImpl{client}
}

func (c *AttendanceServiceHTTPClientImpl) GetMonthlyAttendance(ctx context.Context, in *GetMonthlyAttendanceRequest, opts ...http.CallOption) (*GetMonthlyAttendanceResponse, error) {
	var out GetMonthlyAttendanceResponse
	pattern := "/v1/attendance"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAttendanceServiceGetMonthlyAttendance))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
