// Code generated by ent, DO NOT EDIT.

package model

import (
	"mall-go/module/attendance/service/internal/data/ent/schema"
	"mall-go/module/attendance/service/internal/data/model/attendance"
	"mall-go/module/attendance/service/internal/data/model/employeeshiftschedule"
	"mall-go/module/attendance/service/internal/data/model/overtime"
	"mall-go/module/attendance/service/internal/data/model/shift"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	attendanceFields := schema.Attendance{}.Fields()
	_ = attendanceFields
	// attendanceDescStatus is the schema descriptor for status field.
	attendanceDescStatus := attendanceFields[4].Descriptor()
	// attendance.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	attendance.StatusValidator = attendanceDescStatus.Validators[0].(func(string) error)
	// attendanceDescOvertimeMinutes is the schema descriptor for overtime_minutes field.
	attendanceDescOvertimeMinutes := attendanceFields[6].Descriptor()
	// attendance.DefaultOvertimeMinutes holds the default value on creation for the overtime_minutes field.
	attendance.DefaultOvertimeMinutes = attendanceDescOvertimeMinutes.Default.(int)
	// attendanceDescCreatedAt is the schema descriptor for created_at field.
	attendanceDescCreatedAt := attendanceFields[9].Descriptor()
	// attendance.DefaultCreatedAt holds the default value on creation for the created_at field.
	attendance.DefaultCreatedAt = attendanceDescCreatedAt.Default.(func() time.Time)
	// attendanceDescUpdatedAt is the schema descriptor for updated_at field.
	attendanceDescUpdatedAt := attendanceFields[10].Descriptor()
	// attendance.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	attendance.DefaultUpdatedAt = attendanceDescUpdatedAt.Default.(func() time.Time)
	// attendance.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	attendance.UpdateDefaultUpdatedAt = attendanceDescUpdatedAt.UpdateDefault.(func() time.Time)
	employeeshiftscheduleFields := schema.EmployeeShiftSchedule{}.Fields()
	_ = employeeshiftscheduleFields
	// employeeshiftscheduleDescCreatedAt is the schema descriptor for created_at field.
	employeeshiftscheduleDescCreatedAt := employeeshiftscheduleFields[3].Descriptor()
	// employeeshiftschedule.DefaultCreatedAt holds the default value on creation for the created_at field.
	employeeshiftschedule.DefaultCreatedAt = employeeshiftscheduleDescCreatedAt.Default.(func() time.Time)
	// employeeshiftscheduleDescUpdatedAt is the schema descriptor for updated_at field.
	employeeshiftscheduleDescUpdatedAt := employeeshiftscheduleFields[4].Descriptor()
	// employeeshiftschedule.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	employeeshiftschedule.DefaultUpdatedAt = employeeshiftscheduleDescUpdatedAt.Default.(func() time.Time)
	// employeeshiftschedule.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	employeeshiftschedule.UpdateDefaultUpdatedAt = employeeshiftscheduleDescUpdatedAt.UpdateDefault.(func() time.Time)
	overtimeFields := schema.Overtime{}.Fields()
	_ = overtimeFields
	// overtimeDescStatus is the schema descriptor for status field.
	overtimeDescStatus := overtimeFields[5].Descriptor()
	// overtime.DefaultStatus holds the default value on creation for the status field.
	overtime.DefaultStatus = overtimeDescStatus.Default.(string)
	// overtime.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	overtime.StatusValidator = overtimeDescStatus.Validators[0].(func(string) error)
	// overtimeDescCreatedAt is the schema descriptor for created_at field.
	overtimeDescCreatedAt := overtimeFields[7].Descriptor()
	// overtime.DefaultCreatedAt holds the default value on creation for the created_at field.
	overtime.DefaultCreatedAt = overtimeDescCreatedAt.Default.(func() time.Time)
	// overtimeDescUpdatedAt is the schema descriptor for updated_at field.
	overtimeDescUpdatedAt := overtimeFields[8].Descriptor()
	// overtime.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	overtime.DefaultUpdatedAt = overtimeDescUpdatedAt.Default.(func() time.Time)
	// overtime.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	overtime.UpdateDefaultUpdatedAt = overtimeDescUpdatedAt.UpdateDefault.(func() time.Time)
	shiftFields := schema.Shift{}.Fields()
	_ = shiftFields
	// shiftDescName is the schema descriptor for name field.
	shiftDescName := shiftFields[1].Descriptor()
	// shift.NameValidator is a validator for the "name" field. It is called by the builders before save.
	shift.NameValidator = shiftDescName.Validators[0].(func(string) error)
	// shiftDescBreakDurationMinutes is the schema descriptor for break_duration_minutes field.
	shiftDescBreakDurationMinutes := shiftFields[4].Descriptor()
	// shift.DefaultBreakDurationMinutes holds the default value on creation for the break_duration_minutes field.
	shift.DefaultBreakDurationMinutes = shiftDescBreakDurationMinutes.Default.(int)
	// shiftDescCreatedAt is the schema descriptor for created_at field.
	shiftDescCreatedAt := shiftFields[5].Descriptor()
	// shift.DefaultCreatedAt holds the default value on creation for the created_at field.
	shift.DefaultCreatedAt = shiftDescCreatedAt.Default.(func() time.Time)
	// shiftDescUpdatedAt is the schema descriptor for updated_at field.
	shiftDescUpdatedAt := shiftFields[6].Descriptor()
	// shift.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	shift.DefaultUpdatedAt = shiftDescUpdatedAt.Default.(func() time.Time)
	// shift.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	shift.UpdateDefaultUpdatedAt = shiftDescUpdatedAt.UpdateDefault.(func() time.Time)
}
