server:
  http:
    addr: 0.0.0.0:8005
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9005
    timeout: 1s
data:
  database:
    driver: postgres
    source: "host=127.0.0.1 user=admin password=admin123 dbname=shift port=5432 sslmode=disable TimeZone=Asia/Jakarta"
  redis:
    # employers_db: 4
    addr: 127.0.0.1:6379
    password: ""
    username: ""
    read_timeout: 0.2s
    write_timeout: 0.2s
    TTL: 1000
  kafka:
    addr: 127.0.0.1:19092
    department_topic: "department_topic"
    biometrics_topic: "biometrics_topic"
    partition: 0
    read_timeout: 0.2s
    write_timeout: 0.2s