// Code generated by ent, DO NOT EDIT.

package model

import (
	"mall-go/module/shiftschedule/service/internal/data/ent/schema"
	"mall-go/module/shiftschedule/service/internal/data/model/shiftschedule"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	shiftscheduleFields := schema.ShiftSchedule{}.Fields()
	_ = shiftscheduleFields
	// shiftscheduleDescCreatedAt is the schema descriptor for created_at field.
	shiftscheduleDescCreatedAt := shiftscheduleFields[7].Descriptor()
	// shiftschedule.DefaultCreatedAt holds the default value on creation for the created_at field.
	shiftschedule.DefaultCreatedAt = shiftscheduleDescCreatedAt.Default.(func() time.Time)
	// shiftscheduleDescUpdatedAt is the schema descriptor for updated_at field.
	shiftscheduleDescUpdatedAt := shiftscheduleFields[8].Descriptor()
	// shiftschedule.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	shiftschedule.DefaultUpdatedAt = shiftscheduleDescUpdatedAt.Default.(func() time.Time)
	// shiftschedule.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	shiftschedule.UpdateDefaultUpdatedAt = shiftscheduleDescUpdatedAt.UpdateDefault.(func() time.Time)
}
