// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AttendanceLogColumns holds the columns for the "attendance_log" table.
	AttendanceLogColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_by", Type: field.TypeString, Nullable: true},
		{Name: "updated_by", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "device_ip", Type: field.TypeString},
		{Name: "att_log", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "status", Type: field.TypeInt},
		{Name: "att_date", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "date"}},
	}
	// AttendanceLogTable holds the schema information for the "attendance_log" table.
	AttendanceLogTable = &schema.Table{
		Name:       "attendance_log",
		Columns:    AttendanceLogColumns,
		PrimaryKey: []*schema.Column{AttendanceLogColumns[0]},
	}
	// CronzkColumns holds the columns for the "cronzk" table.
	CronzkColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_by", Type: field.TypeString, Nullable: true},
		{Name: "updated_by", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "spec", Type: field.TypeString},
		{Name: "command", Type: field.TypeString},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "last_run_at", Type: field.TypeTime, Nullable: true},
		{Name: "next_run_at", Type: field.TypeTime, Nullable: true},
	}
	// CronzkTable holds the schema information for the "cronzk" table.
	CronzkTable = &schema.Table{
		Name:       "cronzk",
		Columns:    CronzkColumns,
		PrimaryKey: []*schema.Column{CronzkColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AttendanceLogTable,
		CronzkTable,
	}
)

func init() {
	AttendanceLogTable.Annotation = &entsql.Annotation{
		Table: "attendance_log",
	}
	CronzkTable.Annotation = &entsql.Annotation{
		Table: "cronzk",
	}
}
