// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v5.29.3
// source: api/shift/service/v1/shift.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationShiftCreateShift = "/shift.service.v1.Shift/CreateShift"
const OperationShiftDeleteShift = "/shift.service.v1.Shift/DeleteShift"
const OperationShiftGetShiftID = "/shift.service.v1.Shift/GetShiftID"
const OperationShiftListShift = "/shift.service.v1.Shift/ListShift"
const OperationShiftUpdateShift = "/shift.service.v1.Shift/UpdateShift"

type ShiftHTTPServer interface {
	CreateShift(context.Context, *CreateShiftRequest) (*CreateShiftResponse, error)
	DeleteShift(context.Context, *DeleteShiftRequest) (*DeleteShiftResponse, error)
	GetShiftID(context.Context, *GetShiftIDRequest) (*GetShiftIDResponse, error)
	ListShift(context.Context, *ListShiftRequest) (*ListShiftResponse, error)
	UpdateShift(context.Context, *UpdateShiftRequest) (*UpdateShiftResponse, error)
}

func RegisterShiftHTTPServer(s *http.Server, srv ShiftHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/shifts", _Shift_CreateShift0_HTTP_Handler(srv))
	r.GET("/v1/shifts/{id}", _Shift_GetShiftID0_HTTP_Handler(srv))
	r.GET("/v1/shifts", _Shift_ListShift0_HTTP_Handler(srv))
	r.PUT("/v1/shifts/{id}", _Shift_UpdateShift0_HTTP_Handler(srv))
	r.DELETE("/v1/shifts/{id}", _Shift_DeleteShift0_HTTP_Handler(srv))
}

func _Shift_CreateShift0_HTTP_Handler(srv ShiftHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateShiftRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShiftCreateShift)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateShift(ctx, req.(*CreateShiftRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateShiftResponse)
		return ctx.Result(200, reply)
	}
}

func _Shift_GetShiftID0_HTTP_Handler(srv ShiftHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetShiftIDRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShiftGetShiftID)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetShiftID(ctx, req.(*GetShiftIDRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetShiftIDResponse)
		return ctx.Result(200, reply)
	}
}

func _Shift_ListShift0_HTTP_Handler(srv ShiftHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListShiftRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShiftListShift)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListShift(ctx, req.(*ListShiftRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListShiftResponse)
		return ctx.Result(200, reply)
	}
}

func _Shift_UpdateShift0_HTTP_Handler(srv ShiftHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateShiftRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShiftUpdateShift)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateShift(ctx, req.(*UpdateShiftRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateShiftResponse)
		return ctx.Result(200, reply)
	}
}

func _Shift_DeleteShift0_HTTP_Handler(srv ShiftHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteShiftRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShiftDeleteShift)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteShift(ctx, req.(*DeleteShiftRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteShiftResponse)
		return ctx.Result(200, reply)
	}
}

type ShiftHTTPClient interface {
	CreateShift(ctx context.Context, req *CreateShiftRequest, opts ...http.CallOption) (rsp *CreateShiftResponse, err error)
	DeleteShift(ctx context.Context, req *DeleteShiftRequest, opts ...http.CallOption) (rsp *DeleteShiftResponse, err error)
	GetShiftID(ctx context.Context, req *GetShiftIDRequest, opts ...http.CallOption) (rsp *GetShiftIDResponse, err error)
	ListShift(ctx context.Context, req *ListShiftRequest, opts ...http.CallOption) (rsp *ListShiftResponse, err error)
	UpdateShift(ctx context.Context, req *UpdateShiftRequest, opts ...http.CallOption) (rsp *UpdateShiftResponse, err error)
}

type ShiftHTTPClientImpl struct {
	cc *http.Client
}

func NewShiftHTTPClient(client *http.Client) ShiftHTTPClient {
	return &ShiftHTTPClientImpl{client}
}

func (c *ShiftHTTPClientImpl) CreateShift(ctx context.Context, in *CreateShiftRequest, opts ...http.CallOption) (*CreateShiftResponse, error) {
	var out CreateShiftResponse
	pattern := "/v1/shifts"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationShiftCreateShift))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ShiftHTTPClientImpl) DeleteShift(ctx context.Context, in *DeleteShiftRequest, opts ...http.CallOption) (*DeleteShiftResponse, error) {
	var out DeleteShiftResponse
	pattern := "/v1/shifts/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationShiftDeleteShift))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ShiftHTTPClientImpl) GetShiftID(ctx context.Context, in *GetShiftIDRequest, opts ...http.CallOption) (*GetShiftIDResponse, error) {
	var out GetShiftIDResponse
	pattern := "/v1/shifts/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationShiftGetShiftID))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ShiftHTTPClientImpl) ListShift(ctx context.Context, in *ListShiftRequest, opts ...http.CallOption) (*ListShiftResponse, error) {
	var out ListShiftResponse
	pattern := "/v1/shifts"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationShiftListShift))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ShiftHTTPClientImpl) UpdateShift(ctx context.Context, in *UpdateShiftRequest, opts ...http.CallOption) (*UpdateShiftResponse, error) {
	var out UpdateShiftResponse
	pattern := "/v1/shifts/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationShiftUpdateShift))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
