// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AttendanceLog is the predicate function for attendancelog builders.
type AttendanceLog func(*sql.Selector)
