// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"mall-go/module/attendance/service/internal/biz"
	"mall-go/module/attendance/service/internal/conf"
	"mall-go/module/attendance/service/internal/data"
	"mall-go/module/attendance/service/internal/server"
	"mall-go/module/attendance/service/internal/service"
)

// Injectors from wire.go:

func wireApp(confServer *conf.Server, confData *conf.Data, registry *conf.Registry, logger log.Logger) (*kratos.App, func(), error) {
	client := data.NewEntClient(confData, logger)
	discovery := server.NewDiscovery(registry)
	dataData, cleanup, err := data.NewData(client, logger, discovery)
	if err != nil {
		return nil, nil, err
	}
	employersClient := server.NewEmployersClient(discovery)
	attendanceRepo := data.NewAttendanceRepo(dataData, employersClient, logger)
	departmentClient := server.NewDepartmentClient(discovery)
	attendanceUsecase := biz.NewAttendanceUsecase(attendanceRepo, logger, departmentClient, employersClient)
	attendanceService := service.NewAttendanceService(attendanceUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, attendanceService, logger)
	grpcServer := server.NewGRPCServer(confServer, attendanceService, logger)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, httpServer, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
