server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
devices:
  - ip: 192.168.80.26
  - ip: 192.168.80.27
  - ip: 192.168.80.28
  - ip: 192.168.80.29
  # - ip: 192.168.1.233    
data:
  database:
    driver: postgres
    source: "host=127.0.0.1 user=admin password=admin123 dbname=attendance port=5432 sslmode=disable TimeZone=Asia/Jakarta"
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
