// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/db_sync/service/v1/db_sync.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Example of a data record structure (adjust according to your actual data)
type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"` // Add other fields as per your source database table
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_api_db_sync_service_v1_db_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_api_db_sync_service_v1_db_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_api_db_sync_service_v1_db_sync_proto_rawDescGZIP(), []int{0}
}

func (x *Record) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Record) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Record) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_api_db_sync_service_v1_db_sync_proto protoreflect.FileDescriptor

const file_api_db_sync_service_v1_db_sync_proto_rawDesc = "" +
	"\n" +
	"$api/db_sync/service/v1/db_sync.proto\x12\x12db_sync.service.v1\"N\n" +
	"\x06Record\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription2\b\n" +
	"\x06DbSyncB\x1bZ\x19api/db_sync/service/v1;v1b\x06proto3"

var (
	file_api_db_sync_service_v1_db_sync_proto_rawDescOnce sync.Once
	file_api_db_sync_service_v1_db_sync_proto_rawDescData []byte
)

func file_api_db_sync_service_v1_db_sync_proto_rawDescGZIP() []byte {
	file_api_db_sync_service_v1_db_sync_proto_rawDescOnce.Do(func() {
		file_api_db_sync_service_v1_db_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_db_sync_service_v1_db_sync_proto_rawDesc), len(file_api_db_sync_service_v1_db_sync_proto_rawDesc)))
	})
	return file_api_db_sync_service_v1_db_sync_proto_rawDescData
}

var file_api_db_sync_service_v1_db_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_db_sync_service_v1_db_sync_proto_goTypes = []any{
	(*Record)(nil), // 0: db_sync.service.v1.Record
}
var file_api_db_sync_service_v1_db_sync_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_db_sync_service_v1_db_sync_proto_init() }
func file_api_db_sync_service_v1_db_sync_proto_init() {
	if File_api_db_sync_service_v1_db_sync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_db_sync_service_v1_db_sync_proto_rawDesc), len(file_api_db_sync_service_v1_db_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_db_sync_service_v1_db_sync_proto_goTypes,
		DependencyIndexes: file_api_db_sync_service_v1_db_sync_proto_depIdxs,
		MessageInfos:      file_api_db_sync_service_v1_db_sync_proto_msgTypes,
	}.Build()
	File_api_db_sync_service_v1_db_sync_proto = out.File
	file_api_db_sync_service_v1_db_sync_proto_goTypes = nil
	file_api_db_sync_service_v1_db_sync_proto_depIdxs = nil
}
