// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v5.29.3
// source: api/employers/service/v1/employers.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationEmployersCreateEmployers = "/employers.service.v1.Employers/CreateEmployers"
const OperationEmployersDeleteEmployers = "/employers.service.v1.Employers/DeleteEmployers"
const OperationEmployersGetEmployersByFilter = "/employers.service.v1.Employers/GetEmployersByFilter"
const OperationEmployersGetEmployersDetail = "/employers.service.v1.Employers/GetEmployersDetail"
const OperationEmployersGetEmployersFilterDepartCode = "/employers.service.v1.Employers/GetEmployersFilterDepartCode"
const OperationEmployersGetEmployersID = "/employers.service.v1.Employers/GetEmployersID"
const OperationEmployersGetEmployersKode = "/employers.service.v1.Employers/GetEmployersKode"
const OperationEmployersListEmployers = "/employers.service.v1.Employers/ListEmployers"
const OperationEmployersListEmployersNext = "/employers.service.v1.Employers/ListEmployersNext"
const OperationEmployersUpdateEmployers = "/employers.service.v1.Employers/UpdateEmployers"

type EmployersHTTPServer interface {
	CreateEmployers(context.Context, *CreateEmployersRequest) (*CreateEmployersResponse, error)
	DeleteEmployers(context.Context, *DeleteEmployersRequest) (*DeleteEmployersResponse, error)
	GetEmployersByFilter(context.Context, *GetEmployersByFilterRequest) (*GetEmployersByFilterResponse, error)
	GetEmployersDetail(context.Context, *GetEmployerDetailRequest) (*GetEmployersDetailResponse, error)
	GetEmployersFilterDepartCode(context.Context, *GetEmployersFilterDepartCodeRequest) (*GetEmployersFilterDepartCodeResponse, error)
	GetEmployersID(context.Context, *GetEmployersIDRequest) (*GetEmployersIDResponse, error)
	GetEmployersKode(context.Context, *GetEmployersKodeRequest) (*GetEmployersKodeResponse, error)
	ListEmployers(context.Context, *ListEmployersRequest) (*ListEmployersResponse, error)
	ListEmployersNext(context.Context, *ListEmployersTokenReq) (*ListEmployersResponseNextToken, error)
	UpdateEmployers(context.Context, *UpdateEmployersRequest) (*UpdateEmployersResponse, error)
}

func RegisterEmployersHTTPServer(s *http.Server, srv EmployersHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/employers", _Employers_CreateEmployers0_HTTP_Handler(srv))
	r.PUT("/v1/employers/{id}", _Employers_UpdateEmployers0_HTTP_Handler(srv))
	r.DELETE("/v1/employers/{id}", _Employers_DeleteEmployers0_HTTP_Handler(srv))
	r.GET("/v1/employers/{id}", _Employers_GetEmployersID0_HTTP_Handler(srv))
	r.GET("/v1/employers/{karya_code}", _Employers_GetEmployersKode0_HTTP_Handler(srv))
	r.GET("/v1/employer/{id}", _Employers_GetEmployersDetail0_HTTP_Handler(srv))
	r.GET("/v1/employer/list", _Employers_ListEmployers0_HTTP_Handler(srv))
	r.GET("/v1/employers/listnext", _Employers_ListEmployersNext0_HTTP_Handler(srv))
	r.GET("/v1/employers/filter", _Employers_GetEmployersByFilter0_HTTP_Handler(srv))
	r.GET("/v1/employers/depart", _Employers_GetEmployersFilterDepartCode0_HTTP_Handler(srv))
}

func _Employers_CreateEmployers0_HTTP_Handler(srv EmployersHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateEmployersRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEmployersCreateEmployers)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateEmployers(ctx, req.(*CreateEmployersRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateEmployersResponse)
		return ctx.Result(200, reply)
	}
}

func _Employers_UpdateEmployers0_HTTP_Handler(srv EmployersHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateEmployersRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEmployersUpdateEmployers)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateEmployers(ctx, req.(*UpdateEmployersRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateEmployersResponse)
		return ctx.Result(200, reply)
	}
}

func _Employers_DeleteEmployers0_HTTP_Handler(srv EmployersHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteEmployersRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEmployersDeleteEmployers)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteEmployers(ctx, req.(*DeleteEmployersRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteEmployersResponse)
		return ctx.Result(200, reply)
	}
}

func _Employers_GetEmployersID0_HTTP_Handler(srv EmployersHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetEmployersIDRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEmployersGetEmployersID)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetEmployersID(ctx, req.(*GetEmployersIDRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetEmployersIDResponse)
		return ctx.Result(200, reply)
	}
}

func _Employers_GetEmployersKode0_HTTP_Handler(srv EmployersHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetEmployersKodeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEmployersGetEmployersKode)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetEmployersKode(ctx, req.(*GetEmployersKodeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetEmployersKodeResponse)
		return ctx.Result(200, reply)
	}
}

func _Employers_GetEmployersDetail0_HTTP_Handler(srv EmployersHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetEmployerDetailRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEmployersGetEmployersDetail)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetEmployersDetail(ctx, req.(*GetEmployerDetailRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetEmployersDetailResponse)
		return ctx.Result(200, reply)
	}
}

func _Employers_ListEmployers0_HTTP_Handler(srv EmployersHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListEmployersRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEmployersListEmployers)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListEmployers(ctx, req.(*ListEmployersRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListEmployersResponse)
		return ctx.Result(200, reply)
	}
}

func _Employers_ListEmployersNext0_HTTP_Handler(srv EmployersHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListEmployersTokenReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEmployersListEmployersNext)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListEmployersNext(ctx, req.(*ListEmployersTokenReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListEmployersResponseNextToken)
		return ctx.Result(200, reply)
	}
}

func _Employers_GetEmployersByFilter0_HTTP_Handler(srv EmployersHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetEmployersByFilterRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEmployersGetEmployersByFilter)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetEmployersByFilter(ctx, req.(*GetEmployersByFilterRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetEmployersByFilterResponse)
		return ctx.Result(200, reply)
	}
}

func _Employers_GetEmployersFilterDepartCode0_HTTP_Handler(srv EmployersHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetEmployersFilterDepartCodeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEmployersGetEmployersFilterDepartCode)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetEmployersFilterDepartCode(ctx, req.(*GetEmployersFilterDepartCodeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetEmployersFilterDepartCodeResponse)
		return ctx.Result(200, reply)
	}
}

type EmployersHTTPClient interface {
	CreateEmployers(ctx context.Context, req *CreateEmployersRequest, opts ...http.CallOption) (rsp *CreateEmployersResponse, err error)
	DeleteEmployers(ctx context.Context, req *DeleteEmployersRequest, opts ...http.CallOption) (rsp *DeleteEmployersResponse, err error)
	GetEmployersByFilter(ctx context.Context, req *GetEmployersByFilterRequest, opts ...http.CallOption) (rsp *GetEmployersByFilterResponse, err error)
	GetEmployersDetail(ctx context.Context, req *GetEmployerDetailRequest, opts ...http.CallOption) (rsp *GetEmployersDetailResponse, err error)
	GetEmployersFilterDepartCode(ctx context.Context, req *GetEmployersFilterDepartCodeRequest, opts ...http.CallOption) (rsp *GetEmployersFilterDepartCodeResponse, err error)
	GetEmployersID(ctx context.Context, req *GetEmployersIDRequest, opts ...http.CallOption) (rsp *GetEmployersIDResponse, err error)
	GetEmployersKode(ctx context.Context, req *GetEmployersKodeRequest, opts ...http.CallOption) (rsp *GetEmployersKodeResponse, err error)
	ListEmployers(ctx context.Context, req *ListEmployersRequest, opts ...http.CallOption) (rsp *ListEmployersResponse, err error)
	ListEmployersNext(ctx context.Context, req *ListEmployersTokenReq, opts ...http.CallOption) (rsp *ListEmployersResponseNextToken, err error)
	UpdateEmployers(ctx context.Context, req *UpdateEmployersRequest, opts ...http.CallOption) (rsp *UpdateEmployersResponse, err error)
}

type EmployersHTTPClientImpl struct {
	cc *http.Client
}

func NewEmployersHTTPClient(client *http.Client) EmployersHTTPClient {
	return &EmployersHTTPClientImpl{client}
}

func (c *EmployersHTTPClientImpl) CreateEmployers(ctx context.Context, in *CreateEmployersRequest, opts ...http.CallOption) (*CreateEmployersResponse, error) {
	var out CreateEmployersResponse
	pattern := "/v1/employers"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationEmployersCreateEmployers))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *EmployersHTTPClientImpl) DeleteEmployers(ctx context.Context, in *DeleteEmployersRequest, opts ...http.CallOption) (*DeleteEmployersResponse, error) {
	var out DeleteEmployersResponse
	pattern := "/v1/employers/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationEmployersDeleteEmployers))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *EmployersHTTPClientImpl) GetEmployersByFilter(ctx context.Context, in *GetEmployersByFilterRequest, opts ...http.CallOption) (*GetEmployersByFilterResponse, error) {
	var out GetEmployersByFilterResponse
	pattern := "/v1/employers/filter"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationEmployersGetEmployersByFilter))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *EmployersHTTPClientImpl) GetEmployersDetail(ctx context.Context, in *GetEmployerDetailRequest, opts ...http.CallOption) (*GetEmployersDetailResponse, error) {
	var out GetEmployersDetailResponse
	pattern := "/v1/employer/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationEmployersGetEmployersDetail))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *EmployersHTTPClientImpl) GetEmployersFilterDepartCode(ctx context.Context, in *GetEmployersFilterDepartCodeRequest, opts ...http.CallOption) (*GetEmployersFilterDepartCodeResponse, error) {
	var out GetEmployersFilterDepartCodeResponse
	pattern := "/v1/employers/depart"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationEmployersGetEmployersFilterDepartCode))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *EmployersHTTPClientImpl) GetEmployersID(ctx context.Context, in *GetEmployersIDRequest, opts ...http.CallOption) (*GetEmployersIDResponse, error) {
	var out GetEmployersIDResponse
	pattern := "/v1/employers/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationEmployersGetEmployersID))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *EmployersHTTPClientImpl) GetEmployersKode(ctx context.Context, in *GetEmployersKodeRequest, opts ...http.CallOption) (*GetEmployersKodeResponse, error) {
	var out GetEmployersKodeResponse
	pattern := "/v1/employers/{karya_code}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationEmployersGetEmployersKode))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *EmployersHTTPClientImpl) ListEmployers(ctx context.Context, in *ListEmployersRequest, opts ...http.CallOption) (*ListEmployersResponse, error) {
	var out ListEmployersResponse
	pattern := "/v1/employer/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationEmployersListEmployers))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *EmployersHTTPClientImpl) ListEmployersNext(ctx context.Context, in *ListEmployersTokenReq, opts ...http.CallOption) (*ListEmployersResponseNextToken, error) {
	var out ListEmployersResponseNextToken
	pattern := "/v1/employers/listnext"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationEmployersListEmployersNext))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *EmployersHTTPClientImpl) UpdateEmployers(ctx context.Context, in *UpdateEmployersRequest, opts ...http.CallOption) (*UpdateEmployersResponse, error) {
	var out UpdateEmployersResponse
	pattern := "/v1/employers/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationEmployersUpdateEmployers))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
