server:
  http:
    addr: 0.0.0.0:8006
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9006
    timeout: 1s
data:
  database:
    driver: postgres
    source: "host=127.0.0.1 user=admin password=admin123 dbname=attendance port=5432 sslmode=disable TimeZone=Asia/Jakarta"
  redis:
    addr: 127.0.0.1:6379
    db: 0
    read_timeout: 0.2s
    write_timeout: 0.2s
  kafka:
    addrs:
      - 127.0.0.1:19092
    topic: 'department'
    groupId: 'department.v1'
    username: superuser
    password: secretpassword
