// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: api/shiftschedule/service/v1/shiftschedule.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShiftSchedule_CreateShiftSchedule_FullMethodName = "/shiftschedule.service.v1.ShiftSchedule/CreateShiftSchedule"
	ShiftSchedule_GetShiftScheduleID_FullMethodName  = "/shiftschedule.service.v1.ShiftSchedule/GetShiftScheduleID"
	ShiftSchedule_ListShiftSchedule_FullMethodName   = "/shiftschedule.service.v1.ShiftSchedule/ListShiftSchedule"
	ShiftSchedule_UpdateShiftSchedule_FullMethodName = "/shiftschedule.service.v1.ShiftSchedule/UpdateShiftSchedule"
	ShiftSchedule_DeleteShiftSchedule_FullMethodName = "/shiftschedule.service.v1.ShiftSchedule/DeleteShiftSchedule"
)

// ShiftScheduleClient is the client API for ShiftSchedule service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShiftScheduleClient interface {
	CreateShiftSchedule(ctx context.Context, in *CreateShiftScheduleRequest, opts ...grpc.CallOption) (*CreateShiftScheduleResponse, error)
	GetShiftScheduleID(ctx context.Context, in *GetShiftScheduleRequest, opts ...grpc.CallOption) (*GetShiftScheduleResponse, error)
	ListShiftSchedule(ctx context.Context, in *ListShiftScheduleRequest, opts ...grpc.CallOption) (*ListShiftScheduleResponse, error)
	UpdateShiftSchedule(ctx context.Context, in *UpdateShiftScheduleRequest, opts ...grpc.CallOption) (*UpdateShiftScheduleResponse, error)
	DeleteShiftSchedule(ctx context.Context, in *DeleteShiftScheduleRequest, opts ...grpc.CallOption) (*DeleteShiftScheduleResponse, error)
}

type shiftScheduleClient struct {
	cc grpc.ClientConnInterface
}

func NewShiftScheduleClient(cc grpc.ClientConnInterface) ShiftScheduleClient {
	return &shiftScheduleClient{cc}
}

func (c *shiftScheduleClient) CreateShiftSchedule(ctx context.Context, in *CreateShiftScheduleRequest, opts ...grpc.CallOption) (*CreateShiftScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateShiftScheduleResponse)
	err := c.cc.Invoke(ctx, ShiftSchedule_CreateShiftSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shiftScheduleClient) GetShiftScheduleID(ctx context.Context, in *GetShiftScheduleRequest, opts ...grpc.CallOption) (*GetShiftScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetShiftScheduleResponse)
	err := c.cc.Invoke(ctx, ShiftSchedule_GetShiftScheduleID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shiftScheduleClient) ListShiftSchedule(ctx context.Context, in *ListShiftScheduleRequest, opts ...grpc.CallOption) (*ListShiftScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListShiftScheduleResponse)
	err := c.cc.Invoke(ctx, ShiftSchedule_ListShiftSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shiftScheduleClient) UpdateShiftSchedule(ctx context.Context, in *UpdateShiftScheduleRequest, opts ...grpc.CallOption) (*UpdateShiftScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateShiftScheduleResponse)
	err := c.cc.Invoke(ctx, ShiftSchedule_UpdateShiftSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shiftScheduleClient) DeleteShiftSchedule(ctx context.Context, in *DeleteShiftScheduleRequest, opts ...grpc.CallOption) (*DeleteShiftScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteShiftScheduleResponse)
	err := c.cc.Invoke(ctx, ShiftSchedule_DeleteShiftSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShiftScheduleServer is the server API for ShiftSchedule service.
// All implementations must embed UnimplementedShiftScheduleServer
// for forward compatibility.
type ShiftScheduleServer interface {
	CreateShiftSchedule(context.Context, *CreateShiftScheduleRequest) (*CreateShiftScheduleResponse, error)
	GetShiftScheduleID(context.Context, *GetShiftScheduleRequest) (*GetShiftScheduleResponse, error)
	ListShiftSchedule(context.Context, *ListShiftScheduleRequest) (*ListShiftScheduleResponse, error)
	UpdateShiftSchedule(context.Context, *UpdateShiftScheduleRequest) (*UpdateShiftScheduleResponse, error)
	DeleteShiftSchedule(context.Context, *DeleteShiftScheduleRequest) (*DeleteShiftScheduleResponse, error)
	mustEmbedUnimplementedShiftScheduleServer()
}

// UnimplementedShiftScheduleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShiftScheduleServer struct{}

func (UnimplementedShiftScheduleServer) CreateShiftSchedule(context.Context, *CreateShiftScheduleRequest) (*CreateShiftScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateShiftSchedule not implemented")
}
func (UnimplementedShiftScheduleServer) GetShiftScheduleID(context.Context, *GetShiftScheduleRequest) (*GetShiftScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShiftScheduleID not implemented")
}
func (UnimplementedShiftScheduleServer) ListShiftSchedule(context.Context, *ListShiftScheduleRequest) (*ListShiftScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListShiftSchedule not implemented")
}
func (UnimplementedShiftScheduleServer) UpdateShiftSchedule(context.Context, *UpdateShiftScheduleRequest) (*UpdateShiftScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateShiftSchedule not implemented")
}
func (UnimplementedShiftScheduleServer) DeleteShiftSchedule(context.Context, *DeleteShiftScheduleRequest) (*DeleteShiftScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteShiftSchedule not implemented")
}
func (UnimplementedShiftScheduleServer) mustEmbedUnimplementedShiftScheduleServer() {}
func (UnimplementedShiftScheduleServer) testEmbeddedByValue()                       {}

// UnsafeShiftScheduleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShiftScheduleServer will
// result in compilation errors.
type UnsafeShiftScheduleServer interface {
	mustEmbedUnimplementedShiftScheduleServer()
}

func RegisterShiftScheduleServer(s grpc.ServiceRegistrar, srv ShiftScheduleServer) {
	// If the following call pancis, it indicates UnimplementedShiftScheduleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShiftSchedule_ServiceDesc, srv)
}

func _ShiftSchedule_CreateShiftSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateShiftScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShiftScheduleServer).CreateShiftSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShiftSchedule_CreateShiftSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShiftScheduleServer).CreateShiftSchedule(ctx, req.(*CreateShiftScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShiftSchedule_GetShiftScheduleID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShiftScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShiftScheduleServer).GetShiftScheduleID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShiftSchedule_GetShiftScheduleID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShiftScheduleServer).GetShiftScheduleID(ctx, req.(*GetShiftScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShiftSchedule_ListShiftSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListShiftScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShiftScheduleServer).ListShiftSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShiftSchedule_ListShiftSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShiftScheduleServer).ListShiftSchedule(ctx, req.(*ListShiftScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShiftSchedule_UpdateShiftSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateShiftScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShiftScheduleServer).UpdateShiftSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShiftSchedule_UpdateShiftSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShiftScheduleServer).UpdateShiftSchedule(ctx, req.(*UpdateShiftScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShiftSchedule_DeleteShiftSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteShiftScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShiftScheduleServer).DeleteShiftSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShiftSchedule_DeleteShiftSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShiftScheduleServer).DeleteShiftSchedule(ctx, req.(*DeleteShiftScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShiftSchedule_ServiceDesc is the grpc.ServiceDesc for ShiftSchedule service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShiftSchedule_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shiftschedule.service.v1.ShiftSchedule",
	HandlerType: (*ShiftScheduleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateShiftSchedule",
			Handler:    _ShiftSchedule_CreateShiftSchedule_Handler,
		},
		{
			MethodName: "GetShiftScheduleID",
			Handler:    _ShiftSchedule_GetShiftScheduleID_Handler,
		},
		{
			MethodName: "ListShiftSchedule",
			Handler:    _ShiftSchedule_ListShiftSchedule_Handler,
		},
		{
			MethodName: "UpdateShiftSchedule",
			Handler:    _ShiftSchedule_UpdateShiftSchedule_Handler,
		},
		{
			MethodName: "DeleteShiftSchedule",
			Handler:    _ShiftSchedule_DeleteShiftSchedule_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/shiftschedule/service/v1/shiftschedule.proto",
}
