// Code generated by ent, DO NOT EDIT.

package attendancelog

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the attendancelog type in the database.
	Label = "attendance_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldDeviceIP holds the string denoting the device_ip field in the database.
	FieldDeviceIP = "device_ip"
	// FieldAttLog holds the string denoting the att_log field in the database.
	FieldAttLog = "att_log"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// Table holds the table name of the attendancelog in the database.
	Table = "attendance_logs"
)

// Columns holds all SQL columns for attendancelog fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldDeviceIP,
	FieldAttLog,
	FieldStatus,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the AttendanceLog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByDeviceIP orders the results by the device_ip field.
func ByDeviceIP(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeviceIP, opts...).ToFunc()
}

// ByAttLog orders the results by the att_log field.
func ByAttLog(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttLog, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}
