// Code generated by ent, DO NOT EDIT.

package biometric

import (
	"mall-go/module/biometric/service/internal/data/model/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Biometric {
	return predicate.Biometric(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Biometric {
	return predicate.Biometric(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Biometric {
	return predicate.Biometric(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Biometric {
	return predicate.Biometric(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Biometric {
	return predicate.Biometric(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Biometric {
	return predicate.Biometric(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Biometric {
	return predicate.Biometric(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Biometric {
	return predicate.Biometric(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Biometric {
	return predicate.Biometric(sql.FieldLTE(FieldID, id))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldEQ(FieldUpdatedBy, v))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.Biometric {
	return predicate.Biometric(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.Biometric {
	return predicate.Biometric(sql.FieldEQ(FieldUpdateTime, v))
}

// DeleteTime applies equality check predicate on the "delete_time" field. It's identical to DeleteTimeEQ.
func DeleteTime(v time.Time) predicate.Biometric {
	return predicate.Biometric(sql.FieldEQ(FieldDeleteTime, v))
}

// Fingercode applies equality check predicate on the "fingercode" field. It's identical to FingercodeEQ.
func Fingercode(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldEQ(FieldFingercode, v))
}

// Finger0 applies equality check predicate on the "finger0" field. It's identical to Finger0EQ.
func Finger0(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldEQ(FieldFinger0, v))
}

// Finger1 applies equality check predicate on the "finger1" field. It's identical to Finger1EQ.
func Finger1(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldEQ(FieldFinger1, v))
}

// Finger2 applies equality check predicate on the "finger2" field. It's identical to Finger2EQ.
func Finger2(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldEQ(FieldFinger2, v))
}

// Finger3 applies equality check predicate on the "finger3" field. It's identical to Finger3EQ.
func Finger3(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldEQ(FieldFinger3, v))
}

// Finger4 applies equality check predicate on the "finger4" field. It's identical to Finger4EQ.
func Finger4(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldEQ(FieldFinger4, v))
}

// Finger5 applies equality check predicate on the "finger5" field. It's identical to Finger5EQ.
func Finger5(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldEQ(FieldFinger5, v))
}

// Finger6 applies equality check predicate on the "finger6" field. It's identical to Finger6EQ.
func Finger6(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldEQ(FieldFinger6, v))
}

// Finger7 applies equality check predicate on the "finger7" field. It's identical to Finger7EQ.
func Finger7(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldEQ(FieldFinger7, v))
}

// Finger8 applies equality check predicate on the "finger8" field. It's identical to Finger8EQ.
func Finger8(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldEQ(FieldFinger8, v))
}

// Finger9 applies equality check predicate on the "finger9" field. It's identical to Finger9EQ.
func Finger9(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldEQ(FieldFinger9, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.Biometric {
	return predicate.Biometric(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.Biometric {
	return predicate.Biometric(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.Biometric {
	return predicate.Biometric(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.Biometric {
	return predicate.Biometric(sql.FieldNotNull(FieldCreatedBy))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldContainsFold(FieldCreatedBy, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...string) predicate.Biometric {
	return predicate.Biometric(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...string) predicate.Biometric {
	return predicate.Biometric(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByContains applies the Contains predicate on the "updated_by" field.
func UpdatedByContains(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldContains(FieldUpdatedBy, v))
}

// UpdatedByHasPrefix applies the HasPrefix predicate on the "updated_by" field.
func UpdatedByHasPrefix(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldHasPrefix(FieldUpdatedBy, v))
}

// UpdatedByHasSuffix applies the HasSuffix predicate on the "updated_by" field.
func UpdatedByHasSuffix(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldHasSuffix(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.Biometric {
	return predicate.Biometric(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.Biometric {
	return predicate.Biometric(sql.FieldNotNull(FieldUpdatedBy))
}

// UpdatedByEqualFold applies the EqualFold predicate on the "updated_by" field.
func UpdatedByEqualFold(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldEqualFold(FieldUpdatedBy, v))
}

// UpdatedByContainsFold applies the ContainsFold predicate on the "updated_by" field.
func UpdatedByContainsFold(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldContainsFold(FieldUpdatedBy, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.Biometric {
	return predicate.Biometric(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.Biometric {
	return predicate.Biometric(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.Biometric {
	return predicate.Biometric(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.Biometric {
	return predicate.Biometric(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.Biometric {
	return predicate.Biometric(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.Biometric {
	return predicate.Biometric(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.Biometric {
	return predicate.Biometric(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.Biometric {
	return predicate.Biometric(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.Biometric {
	return predicate.Biometric(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.Biometric {
	return predicate.Biometric(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.Biometric {
	return predicate.Biometric(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.Biometric {
	return predicate.Biometric(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.Biometric {
	return predicate.Biometric(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.Biometric {
	return predicate.Biometric(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.Biometric {
	return predicate.Biometric(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.Biometric {
	return predicate.Biometric(sql.FieldLTE(FieldUpdateTime, v))
}

// DeleteTimeEQ applies the EQ predicate on the "delete_time" field.
func DeleteTimeEQ(v time.Time) predicate.Biometric {
	return predicate.Biometric(sql.FieldEQ(FieldDeleteTime, v))
}

// DeleteTimeNEQ applies the NEQ predicate on the "delete_time" field.
func DeleteTimeNEQ(v time.Time) predicate.Biometric {
	return predicate.Biometric(sql.FieldNEQ(FieldDeleteTime, v))
}

// DeleteTimeIn applies the In predicate on the "delete_time" field.
func DeleteTimeIn(vs ...time.Time) predicate.Biometric {
	return predicate.Biometric(sql.FieldIn(FieldDeleteTime, vs...))
}

// DeleteTimeNotIn applies the NotIn predicate on the "delete_time" field.
func DeleteTimeNotIn(vs ...time.Time) predicate.Biometric {
	return predicate.Biometric(sql.FieldNotIn(FieldDeleteTime, vs...))
}

// DeleteTimeGT applies the GT predicate on the "delete_time" field.
func DeleteTimeGT(v time.Time) predicate.Biometric {
	return predicate.Biometric(sql.FieldGT(FieldDeleteTime, v))
}

// DeleteTimeGTE applies the GTE predicate on the "delete_time" field.
func DeleteTimeGTE(v time.Time) predicate.Biometric {
	return predicate.Biometric(sql.FieldGTE(FieldDeleteTime, v))
}

// DeleteTimeLT applies the LT predicate on the "delete_time" field.
func DeleteTimeLT(v time.Time) predicate.Biometric {
	return predicate.Biometric(sql.FieldLT(FieldDeleteTime, v))
}

// DeleteTimeLTE applies the LTE predicate on the "delete_time" field.
func DeleteTimeLTE(v time.Time) predicate.Biometric {
	return predicate.Biometric(sql.FieldLTE(FieldDeleteTime, v))
}

// DeleteTimeIsNil applies the IsNil predicate on the "delete_time" field.
func DeleteTimeIsNil() predicate.Biometric {
	return predicate.Biometric(sql.FieldIsNull(FieldDeleteTime))
}

// DeleteTimeNotNil applies the NotNil predicate on the "delete_time" field.
func DeleteTimeNotNil() predicate.Biometric {
	return predicate.Biometric(sql.FieldNotNull(FieldDeleteTime))
}

// FingercodeEQ applies the EQ predicate on the "fingercode" field.
func FingercodeEQ(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldEQ(FieldFingercode, v))
}

// FingercodeNEQ applies the NEQ predicate on the "fingercode" field.
func FingercodeNEQ(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldNEQ(FieldFingercode, v))
}

// FingercodeIn applies the In predicate on the "fingercode" field.
func FingercodeIn(vs ...string) predicate.Biometric {
	return predicate.Biometric(sql.FieldIn(FieldFingercode, vs...))
}

// FingercodeNotIn applies the NotIn predicate on the "fingercode" field.
func FingercodeNotIn(vs ...string) predicate.Biometric {
	return predicate.Biometric(sql.FieldNotIn(FieldFingercode, vs...))
}

// FingercodeGT applies the GT predicate on the "fingercode" field.
func FingercodeGT(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldGT(FieldFingercode, v))
}

// FingercodeGTE applies the GTE predicate on the "fingercode" field.
func FingercodeGTE(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldGTE(FieldFingercode, v))
}

// FingercodeLT applies the LT predicate on the "fingercode" field.
func FingercodeLT(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldLT(FieldFingercode, v))
}

// FingercodeLTE applies the LTE predicate on the "fingercode" field.
func FingercodeLTE(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldLTE(FieldFingercode, v))
}

// FingercodeContains applies the Contains predicate on the "fingercode" field.
func FingercodeContains(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldContains(FieldFingercode, v))
}

// FingercodeHasPrefix applies the HasPrefix predicate on the "fingercode" field.
func FingercodeHasPrefix(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldHasPrefix(FieldFingercode, v))
}

// FingercodeHasSuffix applies the HasSuffix predicate on the "fingercode" field.
func FingercodeHasSuffix(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldHasSuffix(FieldFingercode, v))
}

// FingercodeIsNil applies the IsNil predicate on the "fingercode" field.
func FingercodeIsNil() predicate.Biometric {
	return predicate.Biometric(sql.FieldIsNull(FieldFingercode))
}

// FingercodeNotNil applies the NotNil predicate on the "fingercode" field.
func FingercodeNotNil() predicate.Biometric {
	return predicate.Biometric(sql.FieldNotNull(FieldFingercode))
}

// FingercodeEqualFold applies the EqualFold predicate on the "fingercode" field.
func FingercodeEqualFold(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldEqualFold(FieldFingercode, v))
}

// FingercodeContainsFold applies the ContainsFold predicate on the "fingercode" field.
func FingercodeContainsFold(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldContainsFold(FieldFingercode, v))
}

// Finger0EQ applies the EQ predicate on the "finger0" field.
func Finger0EQ(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldEQ(FieldFinger0, v))
}

// Finger0NEQ applies the NEQ predicate on the "finger0" field.
func Finger0NEQ(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldNEQ(FieldFinger0, v))
}

// Finger0In applies the In predicate on the "finger0" field.
func Finger0In(vs ...string) predicate.Biometric {
	return predicate.Biometric(sql.FieldIn(FieldFinger0, vs...))
}

// Finger0NotIn applies the NotIn predicate on the "finger0" field.
func Finger0NotIn(vs ...string) predicate.Biometric {
	return predicate.Biometric(sql.FieldNotIn(FieldFinger0, vs...))
}

// Finger0GT applies the GT predicate on the "finger0" field.
func Finger0GT(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldGT(FieldFinger0, v))
}

// Finger0GTE applies the GTE predicate on the "finger0" field.
func Finger0GTE(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldGTE(FieldFinger0, v))
}

// Finger0LT applies the LT predicate on the "finger0" field.
func Finger0LT(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldLT(FieldFinger0, v))
}

// Finger0LTE applies the LTE predicate on the "finger0" field.
func Finger0LTE(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldLTE(FieldFinger0, v))
}

// Finger0Contains applies the Contains predicate on the "finger0" field.
func Finger0Contains(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldContains(FieldFinger0, v))
}

// Finger0HasPrefix applies the HasPrefix predicate on the "finger0" field.
func Finger0HasPrefix(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldHasPrefix(FieldFinger0, v))
}

// Finger0HasSuffix applies the HasSuffix predicate on the "finger0" field.
func Finger0HasSuffix(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldHasSuffix(FieldFinger0, v))
}

// Finger0IsNil applies the IsNil predicate on the "finger0" field.
func Finger0IsNil() predicate.Biometric {
	return predicate.Biometric(sql.FieldIsNull(FieldFinger0))
}

// Finger0NotNil applies the NotNil predicate on the "finger0" field.
func Finger0NotNil() predicate.Biometric {
	return predicate.Biometric(sql.FieldNotNull(FieldFinger0))
}

// Finger0EqualFold applies the EqualFold predicate on the "finger0" field.
func Finger0EqualFold(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldEqualFold(FieldFinger0, v))
}

// Finger0ContainsFold applies the ContainsFold predicate on the "finger0" field.
func Finger0ContainsFold(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldContainsFold(FieldFinger0, v))
}

// Finger1EQ applies the EQ predicate on the "finger1" field.
func Finger1EQ(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldEQ(FieldFinger1, v))
}

// Finger1NEQ applies the NEQ predicate on the "finger1" field.
func Finger1NEQ(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldNEQ(FieldFinger1, v))
}

// Finger1In applies the In predicate on the "finger1" field.
func Finger1In(vs ...string) predicate.Biometric {
	return predicate.Biometric(sql.FieldIn(FieldFinger1, vs...))
}

// Finger1NotIn applies the NotIn predicate on the "finger1" field.
func Finger1NotIn(vs ...string) predicate.Biometric {
	return predicate.Biometric(sql.FieldNotIn(FieldFinger1, vs...))
}

// Finger1GT applies the GT predicate on the "finger1" field.
func Finger1GT(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldGT(FieldFinger1, v))
}

// Finger1GTE applies the GTE predicate on the "finger1" field.
func Finger1GTE(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldGTE(FieldFinger1, v))
}

// Finger1LT applies the LT predicate on the "finger1" field.
func Finger1LT(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldLT(FieldFinger1, v))
}

// Finger1LTE applies the LTE predicate on the "finger1" field.
func Finger1LTE(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldLTE(FieldFinger1, v))
}

// Finger1Contains applies the Contains predicate on the "finger1" field.
func Finger1Contains(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldContains(FieldFinger1, v))
}

// Finger1HasPrefix applies the HasPrefix predicate on the "finger1" field.
func Finger1HasPrefix(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldHasPrefix(FieldFinger1, v))
}

// Finger1HasSuffix applies the HasSuffix predicate on the "finger1" field.
func Finger1HasSuffix(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldHasSuffix(FieldFinger1, v))
}

// Finger1IsNil applies the IsNil predicate on the "finger1" field.
func Finger1IsNil() predicate.Biometric {
	return predicate.Biometric(sql.FieldIsNull(FieldFinger1))
}

// Finger1NotNil applies the NotNil predicate on the "finger1" field.
func Finger1NotNil() predicate.Biometric {
	return predicate.Biometric(sql.FieldNotNull(FieldFinger1))
}

// Finger1EqualFold applies the EqualFold predicate on the "finger1" field.
func Finger1EqualFold(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldEqualFold(FieldFinger1, v))
}

// Finger1ContainsFold applies the ContainsFold predicate on the "finger1" field.
func Finger1ContainsFold(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldContainsFold(FieldFinger1, v))
}

// Finger2EQ applies the EQ predicate on the "finger2" field.
func Finger2EQ(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldEQ(FieldFinger2, v))
}

// Finger2NEQ applies the NEQ predicate on the "finger2" field.
func Finger2NEQ(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldNEQ(FieldFinger2, v))
}

// Finger2In applies the In predicate on the "finger2" field.
func Finger2In(vs ...string) predicate.Biometric {
	return predicate.Biometric(sql.FieldIn(FieldFinger2, vs...))
}

// Finger2NotIn applies the NotIn predicate on the "finger2" field.
func Finger2NotIn(vs ...string) predicate.Biometric {
	return predicate.Biometric(sql.FieldNotIn(FieldFinger2, vs...))
}

// Finger2GT applies the GT predicate on the "finger2" field.
func Finger2GT(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldGT(FieldFinger2, v))
}

// Finger2GTE applies the GTE predicate on the "finger2" field.
func Finger2GTE(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldGTE(FieldFinger2, v))
}

// Finger2LT applies the LT predicate on the "finger2" field.
func Finger2LT(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldLT(FieldFinger2, v))
}

// Finger2LTE applies the LTE predicate on the "finger2" field.
func Finger2LTE(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldLTE(FieldFinger2, v))
}

// Finger2Contains applies the Contains predicate on the "finger2" field.
func Finger2Contains(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldContains(FieldFinger2, v))
}

// Finger2HasPrefix applies the HasPrefix predicate on the "finger2" field.
func Finger2HasPrefix(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldHasPrefix(FieldFinger2, v))
}

// Finger2HasSuffix applies the HasSuffix predicate on the "finger2" field.
func Finger2HasSuffix(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldHasSuffix(FieldFinger2, v))
}

// Finger2IsNil applies the IsNil predicate on the "finger2" field.
func Finger2IsNil() predicate.Biometric {
	return predicate.Biometric(sql.FieldIsNull(FieldFinger2))
}

// Finger2NotNil applies the NotNil predicate on the "finger2" field.
func Finger2NotNil() predicate.Biometric {
	return predicate.Biometric(sql.FieldNotNull(FieldFinger2))
}

// Finger2EqualFold applies the EqualFold predicate on the "finger2" field.
func Finger2EqualFold(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldEqualFold(FieldFinger2, v))
}

// Finger2ContainsFold applies the ContainsFold predicate on the "finger2" field.
func Finger2ContainsFold(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldContainsFold(FieldFinger2, v))
}

// Finger3EQ applies the EQ predicate on the "finger3" field.
func Finger3EQ(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldEQ(FieldFinger3, v))
}

// Finger3NEQ applies the NEQ predicate on the "finger3" field.
func Finger3NEQ(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldNEQ(FieldFinger3, v))
}

// Finger3In applies the In predicate on the "finger3" field.
func Finger3In(vs ...string) predicate.Biometric {
	return predicate.Biometric(sql.FieldIn(FieldFinger3, vs...))
}

// Finger3NotIn applies the NotIn predicate on the "finger3" field.
func Finger3NotIn(vs ...string) predicate.Biometric {
	return predicate.Biometric(sql.FieldNotIn(FieldFinger3, vs...))
}

// Finger3GT applies the GT predicate on the "finger3" field.
func Finger3GT(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldGT(FieldFinger3, v))
}

// Finger3GTE applies the GTE predicate on the "finger3" field.
func Finger3GTE(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldGTE(FieldFinger3, v))
}

// Finger3LT applies the LT predicate on the "finger3" field.
func Finger3LT(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldLT(FieldFinger3, v))
}

// Finger3LTE applies the LTE predicate on the "finger3" field.
func Finger3LTE(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldLTE(FieldFinger3, v))
}

// Finger3Contains applies the Contains predicate on the "finger3" field.
func Finger3Contains(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldContains(FieldFinger3, v))
}

// Finger3HasPrefix applies the HasPrefix predicate on the "finger3" field.
func Finger3HasPrefix(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldHasPrefix(FieldFinger3, v))
}

// Finger3HasSuffix applies the HasSuffix predicate on the "finger3" field.
func Finger3HasSuffix(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldHasSuffix(FieldFinger3, v))
}

// Finger3IsNil applies the IsNil predicate on the "finger3" field.
func Finger3IsNil() predicate.Biometric {
	return predicate.Biometric(sql.FieldIsNull(FieldFinger3))
}

// Finger3NotNil applies the NotNil predicate on the "finger3" field.
func Finger3NotNil() predicate.Biometric {
	return predicate.Biometric(sql.FieldNotNull(FieldFinger3))
}

// Finger3EqualFold applies the EqualFold predicate on the "finger3" field.
func Finger3EqualFold(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldEqualFold(FieldFinger3, v))
}

// Finger3ContainsFold applies the ContainsFold predicate on the "finger3" field.
func Finger3ContainsFold(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldContainsFold(FieldFinger3, v))
}

// Finger4EQ applies the EQ predicate on the "finger4" field.
func Finger4EQ(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldEQ(FieldFinger4, v))
}

// Finger4NEQ applies the NEQ predicate on the "finger4" field.
func Finger4NEQ(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldNEQ(FieldFinger4, v))
}

// Finger4In applies the In predicate on the "finger4" field.
func Finger4In(vs ...string) predicate.Biometric {
	return predicate.Biometric(sql.FieldIn(FieldFinger4, vs...))
}

// Finger4NotIn applies the NotIn predicate on the "finger4" field.
func Finger4NotIn(vs ...string) predicate.Biometric {
	return predicate.Biometric(sql.FieldNotIn(FieldFinger4, vs...))
}

// Finger4GT applies the GT predicate on the "finger4" field.
func Finger4GT(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldGT(FieldFinger4, v))
}

// Finger4GTE applies the GTE predicate on the "finger4" field.
func Finger4GTE(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldGTE(FieldFinger4, v))
}

// Finger4LT applies the LT predicate on the "finger4" field.
func Finger4LT(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldLT(FieldFinger4, v))
}

// Finger4LTE applies the LTE predicate on the "finger4" field.
func Finger4LTE(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldLTE(FieldFinger4, v))
}

// Finger4Contains applies the Contains predicate on the "finger4" field.
func Finger4Contains(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldContains(FieldFinger4, v))
}

// Finger4HasPrefix applies the HasPrefix predicate on the "finger4" field.
func Finger4HasPrefix(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldHasPrefix(FieldFinger4, v))
}

// Finger4HasSuffix applies the HasSuffix predicate on the "finger4" field.
func Finger4HasSuffix(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldHasSuffix(FieldFinger4, v))
}

// Finger4IsNil applies the IsNil predicate on the "finger4" field.
func Finger4IsNil() predicate.Biometric {
	return predicate.Biometric(sql.FieldIsNull(FieldFinger4))
}

// Finger4NotNil applies the NotNil predicate on the "finger4" field.
func Finger4NotNil() predicate.Biometric {
	return predicate.Biometric(sql.FieldNotNull(FieldFinger4))
}

// Finger4EqualFold applies the EqualFold predicate on the "finger4" field.
func Finger4EqualFold(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldEqualFold(FieldFinger4, v))
}

// Finger4ContainsFold applies the ContainsFold predicate on the "finger4" field.
func Finger4ContainsFold(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldContainsFold(FieldFinger4, v))
}

// Finger5EQ applies the EQ predicate on the "finger5" field.
func Finger5EQ(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldEQ(FieldFinger5, v))
}

// Finger5NEQ applies the NEQ predicate on the "finger5" field.
func Finger5NEQ(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldNEQ(FieldFinger5, v))
}

// Finger5In applies the In predicate on the "finger5" field.
func Finger5In(vs ...string) predicate.Biometric {
	return predicate.Biometric(sql.FieldIn(FieldFinger5, vs...))
}

// Finger5NotIn applies the NotIn predicate on the "finger5" field.
func Finger5NotIn(vs ...string) predicate.Biometric {
	return predicate.Biometric(sql.FieldNotIn(FieldFinger5, vs...))
}

// Finger5GT applies the GT predicate on the "finger5" field.
func Finger5GT(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldGT(FieldFinger5, v))
}

// Finger5GTE applies the GTE predicate on the "finger5" field.
func Finger5GTE(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldGTE(FieldFinger5, v))
}

// Finger5LT applies the LT predicate on the "finger5" field.
func Finger5LT(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldLT(FieldFinger5, v))
}

// Finger5LTE applies the LTE predicate on the "finger5" field.
func Finger5LTE(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldLTE(FieldFinger5, v))
}

// Finger5Contains applies the Contains predicate on the "finger5" field.
func Finger5Contains(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldContains(FieldFinger5, v))
}

// Finger5HasPrefix applies the HasPrefix predicate on the "finger5" field.
func Finger5HasPrefix(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldHasPrefix(FieldFinger5, v))
}

// Finger5HasSuffix applies the HasSuffix predicate on the "finger5" field.
func Finger5HasSuffix(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldHasSuffix(FieldFinger5, v))
}

// Finger5IsNil applies the IsNil predicate on the "finger5" field.
func Finger5IsNil() predicate.Biometric {
	return predicate.Biometric(sql.FieldIsNull(FieldFinger5))
}

// Finger5NotNil applies the NotNil predicate on the "finger5" field.
func Finger5NotNil() predicate.Biometric {
	return predicate.Biometric(sql.FieldNotNull(FieldFinger5))
}

// Finger5EqualFold applies the EqualFold predicate on the "finger5" field.
func Finger5EqualFold(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldEqualFold(FieldFinger5, v))
}

// Finger5ContainsFold applies the ContainsFold predicate on the "finger5" field.
func Finger5ContainsFold(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldContainsFold(FieldFinger5, v))
}

// Finger6EQ applies the EQ predicate on the "finger6" field.
func Finger6EQ(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldEQ(FieldFinger6, v))
}

// Finger6NEQ applies the NEQ predicate on the "finger6" field.
func Finger6NEQ(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldNEQ(FieldFinger6, v))
}

// Finger6In applies the In predicate on the "finger6" field.
func Finger6In(vs ...string) predicate.Biometric {
	return predicate.Biometric(sql.FieldIn(FieldFinger6, vs...))
}

// Finger6NotIn applies the NotIn predicate on the "finger6" field.
func Finger6NotIn(vs ...string) predicate.Biometric {
	return predicate.Biometric(sql.FieldNotIn(FieldFinger6, vs...))
}

// Finger6GT applies the GT predicate on the "finger6" field.
func Finger6GT(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldGT(FieldFinger6, v))
}

// Finger6GTE applies the GTE predicate on the "finger6" field.
func Finger6GTE(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldGTE(FieldFinger6, v))
}

// Finger6LT applies the LT predicate on the "finger6" field.
func Finger6LT(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldLT(FieldFinger6, v))
}

// Finger6LTE applies the LTE predicate on the "finger6" field.
func Finger6LTE(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldLTE(FieldFinger6, v))
}

// Finger6Contains applies the Contains predicate on the "finger6" field.
func Finger6Contains(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldContains(FieldFinger6, v))
}

// Finger6HasPrefix applies the HasPrefix predicate on the "finger6" field.
func Finger6HasPrefix(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldHasPrefix(FieldFinger6, v))
}

// Finger6HasSuffix applies the HasSuffix predicate on the "finger6" field.
func Finger6HasSuffix(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldHasSuffix(FieldFinger6, v))
}

// Finger6IsNil applies the IsNil predicate on the "finger6" field.
func Finger6IsNil() predicate.Biometric {
	return predicate.Biometric(sql.FieldIsNull(FieldFinger6))
}

// Finger6NotNil applies the NotNil predicate on the "finger6" field.
func Finger6NotNil() predicate.Biometric {
	return predicate.Biometric(sql.FieldNotNull(FieldFinger6))
}

// Finger6EqualFold applies the EqualFold predicate on the "finger6" field.
func Finger6EqualFold(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldEqualFold(FieldFinger6, v))
}

// Finger6ContainsFold applies the ContainsFold predicate on the "finger6" field.
func Finger6ContainsFold(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldContainsFold(FieldFinger6, v))
}

// Finger7EQ applies the EQ predicate on the "finger7" field.
func Finger7EQ(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldEQ(FieldFinger7, v))
}

// Finger7NEQ applies the NEQ predicate on the "finger7" field.
func Finger7NEQ(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldNEQ(FieldFinger7, v))
}

// Finger7In applies the In predicate on the "finger7" field.
func Finger7In(vs ...string) predicate.Biometric {
	return predicate.Biometric(sql.FieldIn(FieldFinger7, vs...))
}

// Finger7NotIn applies the NotIn predicate on the "finger7" field.
func Finger7NotIn(vs ...string) predicate.Biometric {
	return predicate.Biometric(sql.FieldNotIn(FieldFinger7, vs...))
}

// Finger7GT applies the GT predicate on the "finger7" field.
func Finger7GT(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldGT(FieldFinger7, v))
}

// Finger7GTE applies the GTE predicate on the "finger7" field.
func Finger7GTE(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldGTE(FieldFinger7, v))
}

// Finger7LT applies the LT predicate on the "finger7" field.
func Finger7LT(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldLT(FieldFinger7, v))
}

// Finger7LTE applies the LTE predicate on the "finger7" field.
func Finger7LTE(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldLTE(FieldFinger7, v))
}

// Finger7Contains applies the Contains predicate on the "finger7" field.
func Finger7Contains(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldContains(FieldFinger7, v))
}

// Finger7HasPrefix applies the HasPrefix predicate on the "finger7" field.
func Finger7HasPrefix(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldHasPrefix(FieldFinger7, v))
}

// Finger7HasSuffix applies the HasSuffix predicate on the "finger7" field.
func Finger7HasSuffix(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldHasSuffix(FieldFinger7, v))
}

// Finger7IsNil applies the IsNil predicate on the "finger7" field.
func Finger7IsNil() predicate.Biometric {
	return predicate.Biometric(sql.FieldIsNull(FieldFinger7))
}

// Finger7NotNil applies the NotNil predicate on the "finger7" field.
func Finger7NotNil() predicate.Biometric {
	return predicate.Biometric(sql.FieldNotNull(FieldFinger7))
}

// Finger7EqualFold applies the EqualFold predicate on the "finger7" field.
func Finger7EqualFold(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldEqualFold(FieldFinger7, v))
}

// Finger7ContainsFold applies the ContainsFold predicate on the "finger7" field.
func Finger7ContainsFold(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldContainsFold(FieldFinger7, v))
}

// Finger8EQ applies the EQ predicate on the "finger8" field.
func Finger8EQ(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldEQ(FieldFinger8, v))
}

// Finger8NEQ applies the NEQ predicate on the "finger8" field.
func Finger8NEQ(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldNEQ(FieldFinger8, v))
}

// Finger8In applies the In predicate on the "finger8" field.
func Finger8In(vs ...string) predicate.Biometric {
	return predicate.Biometric(sql.FieldIn(FieldFinger8, vs...))
}

// Finger8NotIn applies the NotIn predicate on the "finger8" field.
func Finger8NotIn(vs ...string) predicate.Biometric {
	return predicate.Biometric(sql.FieldNotIn(FieldFinger8, vs...))
}

// Finger8GT applies the GT predicate on the "finger8" field.
func Finger8GT(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldGT(FieldFinger8, v))
}

// Finger8GTE applies the GTE predicate on the "finger8" field.
func Finger8GTE(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldGTE(FieldFinger8, v))
}

// Finger8LT applies the LT predicate on the "finger8" field.
func Finger8LT(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldLT(FieldFinger8, v))
}

// Finger8LTE applies the LTE predicate on the "finger8" field.
func Finger8LTE(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldLTE(FieldFinger8, v))
}

// Finger8Contains applies the Contains predicate on the "finger8" field.
func Finger8Contains(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldContains(FieldFinger8, v))
}

// Finger8HasPrefix applies the HasPrefix predicate on the "finger8" field.
func Finger8HasPrefix(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldHasPrefix(FieldFinger8, v))
}

// Finger8HasSuffix applies the HasSuffix predicate on the "finger8" field.
func Finger8HasSuffix(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldHasSuffix(FieldFinger8, v))
}

// Finger8IsNil applies the IsNil predicate on the "finger8" field.
func Finger8IsNil() predicate.Biometric {
	return predicate.Biometric(sql.FieldIsNull(FieldFinger8))
}

// Finger8NotNil applies the NotNil predicate on the "finger8" field.
func Finger8NotNil() predicate.Biometric {
	return predicate.Biometric(sql.FieldNotNull(FieldFinger8))
}

// Finger8EqualFold applies the EqualFold predicate on the "finger8" field.
func Finger8EqualFold(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldEqualFold(FieldFinger8, v))
}

// Finger8ContainsFold applies the ContainsFold predicate on the "finger8" field.
func Finger8ContainsFold(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldContainsFold(FieldFinger8, v))
}

// Finger9EQ applies the EQ predicate on the "finger9" field.
func Finger9EQ(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldEQ(FieldFinger9, v))
}

// Finger9NEQ applies the NEQ predicate on the "finger9" field.
func Finger9NEQ(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldNEQ(FieldFinger9, v))
}

// Finger9In applies the In predicate on the "finger9" field.
func Finger9In(vs ...string) predicate.Biometric {
	return predicate.Biometric(sql.FieldIn(FieldFinger9, vs...))
}

// Finger9NotIn applies the NotIn predicate on the "finger9" field.
func Finger9NotIn(vs ...string) predicate.Biometric {
	return predicate.Biometric(sql.FieldNotIn(FieldFinger9, vs...))
}

// Finger9GT applies the GT predicate on the "finger9" field.
func Finger9GT(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldGT(FieldFinger9, v))
}

// Finger9GTE applies the GTE predicate on the "finger9" field.
func Finger9GTE(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldGTE(FieldFinger9, v))
}

// Finger9LT applies the LT predicate on the "finger9" field.
func Finger9LT(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldLT(FieldFinger9, v))
}

// Finger9LTE applies the LTE predicate on the "finger9" field.
func Finger9LTE(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldLTE(FieldFinger9, v))
}

// Finger9Contains applies the Contains predicate on the "finger9" field.
func Finger9Contains(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldContains(FieldFinger9, v))
}

// Finger9HasPrefix applies the HasPrefix predicate on the "finger9" field.
func Finger9HasPrefix(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldHasPrefix(FieldFinger9, v))
}

// Finger9HasSuffix applies the HasSuffix predicate on the "finger9" field.
func Finger9HasSuffix(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldHasSuffix(FieldFinger9, v))
}

// Finger9IsNil applies the IsNil predicate on the "finger9" field.
func Finger9IsNil() predicate.Biometric {
	return predicate.Biometric(sql.FieldIsNull(FieldFinger9))
}

// Finger9NotNil applies the NotNil predicate on the "finger9" field.
func Finger9NotNil() predicate.Biometric {
	return predicate.Biometric(sql.FieldNotNull(FieldFinger9))
}

// Finger9EqualFold applies the EqualFold predicate on the "finger9" field.
func Finger9EqualFold(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldEqualFold(FieldFinger9, v))
}

// Finger9ContainsFold applies the ContainsFold predicate on the "finger9" field.
func Finger9ContainsFold(v string) predicate.Biometric {
	return predicate.Biometric(sql.FieldContainsFold(FieldFinger9, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Biometric) predicate.Biometric {
	return predicate.Biometric(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Biometric) predicate.Biometric {
	return predicate.Biometric(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Biometric) predicate.Biometric {
	return predicate.Biometric(sql.NotPredicates(p))
}
