// Code generated by ent, DO NOT EDIT.

package model

import (
	"context"
	"errors"
	"fmt"
	"mall-go/module/log-downloader-service/internal/db/model/attendancelog"
	"mall-go/module/log-downloader-service/internal/db/model/predicate"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeAttendanceLog = "AttendanceLog"
)

// AttendanceLogMutation represents an operation that mutates the AttendanceLog nodes in the graph.
type AttendanceLogMutation struct {
	config
	op            Op
	typ           string
	id            *int64
	user_id       *int64
	adduser_id    *int64
	device_ip     *string
	att_log       *time.Time
	status        *int
	addstatus     *int
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*AttendanceLog, error)
	predicates    []predicate.AttendanceLog
}

var _ ent.Mutation = (*AttendanceLogMutation)(nil)

// attendancelogOption allows management of the mutation configuration using functional options.
type attendancelogOption func(*AttendanceLogMutation)

// newAttendanceLogMutation creates new mutation for the AttendanceLog entity.
func newAttendanceLogMutation(c config, op Op, opts ...attendancelogOption) *AttendanceLogMutation {
	m := &AttendanceLogMutation{
		config:        c,
		op:            op,
		typ:           TypeAttendanceLog,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withAttendanceLogID sets the ID field of the mutation.
func withAttendanceLogID(id int64) attendancelogOption {
	return func(m *AttendanceLogMutation) {
		var (
			err   error
			once  sync.Once
			value *AttendanceLog
		)
		m.oldValue = func(ctx context.Context) (*AttendanceLog, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().AttendanceLog.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withAttendanceLog sets the old AttendanceLog of the mutation.
func withAttendanceLog(node *AttendanceLog) attendancelogOption {
	return func(m *AttendanceLogMutation) {
		m.oldValue = func(context.Context) (*AttendanceLog, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m AttendanceLogMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m AttendanceLogMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("model: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *AttendanceLogMutation) ID() (id int64, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *AttendanceLogMutation) IDs(ctx context.Context) ([]int64, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int64{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().AttendanceLog.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetUserID sets the "user_id" field.
func (m *AttendanceLogMutation) SetUserID(i int64) {
	m.user_id = &i
	m.adduser_id = nil
}

// UserID returns the value of the "user_id" field in the mutation.
func (m *AttendanceLogMutation) UserID() (r int64, exists bool) {
	v := m.user_id
	if v == nil {
		return
	}
	return *v, true
}

// OldUserID returns the old "user_id" field's value of the AttendanceLog entity.
// If the AttendanceLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AttendanceLogMutation) OldUserID(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUserID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUserID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUserID: %w", err)
	}
	return oldValue.UserID, nil
}

// AddUserID adds i to the "user_id" field.
func (m *AttendanceLogMutation) AddUserID(i int64) {
	if m.adduser_id != nil {
		*m.adduser_id += i
	} else {
		m.adduser_id = &i
	}
}

// AddedUserID returns the value that was added to the "user_id" field in this mutation.
func (m *AttendanceLogMutation) AddedUserID() (r int64, exists bool) {
	v := m.adduser_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetUserID resets all changes to the "user_id" field.
func (m *AttendanceLogMutation) ResetUserID() {
	m.user_id = nil
	m.adduser_id = nil
}

// SetDeviceIP sets the "device_ip" field.
func (m *AttendanceLogMutation) SetDeviceIP(s string) {
	m.device_ip = &s
}

// DeviceIP returns the value of the "device_ip" field in the mutation.
func (m *AttendanceLogMutation) DeviceIP() (r string, exists bool) {
	v := m.device_ip
	if v == nil {
		return
	}
	return *v, true
}

// OldDeviceIP returns the old "device_ip" field's value of the AttendanceLog entity.
// If the AttendanceLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AttendanceLogMutation) OldDeviceIP(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDeviceIP is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDeviceIP requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDeviceIP: %w", err)
	}
	return oldValue.DeviceIP, nil
}

// ResetDeviceIP resets all changes to the "device_ip" field.
func (m *AttendanceLogMutation) ResetDeviceIP() {
	m.device_ip = nil
}

// SetAttLog sets the "att_log" field.
func (m *AttendanceLogMutation) SetAttLog(t time.Time) {
	m.att_log = &t
}

// AttLog returns the value of the "att_log" field in the mutation.
func (m *AttendanceLogMutation) AttLog() (r time.Time, exists bool) {
	v := m.att_log
	if v == nil {
		return
	}
	return *v, true
}

// OldAttLog returns the old "att_log" field's value of the AttendanceLog entity.
// If the AttendanceLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AttendanceLogMutation) OldAttLog(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAttLog is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAttLog requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAttLog: %w", err)
	}
	return oldValue.AttLog, nil
}

// ResetAttLog resets all changes to the "att_log" field.
func (m *AttendanceLogMutation) ResetAttLog() {
	m.att_log = nil
}

// SetStatus sets the "status" field.
func (m *AttendanceLogMutation) SetStatus(i int) {
	m.status = &i
	m.addstatus = nil
}

// Status returns the value of the "status" field in the mutation.
func (m *AttendanceLogMutation) Status() (r int, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the AttendanceLog entity.
// If the AttendanceLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AttendanceLogMutation) OldStatus(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// AddStatus adds i to the "status" field.
func (m *AttendanceLogMutation) AddStatus(i int) {
	if m.addstatus != nil {
		*m.addstatus += i
	} else {
		m.addstatus = &i
	}
}

// AddedStatus returns the value that was added to the "status" field in this mutation.
func (m *AttendanceLogMutation) AddedStatus() (r int, exists bool) {
	v := m.addstatus
	if v == nil {
		return
	}
	return *v, true
}

// ResetStatus resets all changes to the "status" field.
func (m *AttendanceLogMutation) ResetStatus() {
	m.status = nil
	m.addstatus = nil
}

// Where appends a list predicates to the AttendanceLogMutation builder.
func (m *AttendanceLogMutation) Where(ps ...predicate.AttendanceLog) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the AttendanceLogMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *AttendanceLogMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.AttendanceLog, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *AttendanceLogMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *AttendanceLogMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (AttendanceLog).
func (m *AttendanceLogMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *AttendanceLogMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.user_id != nil {
		fields = append(fields, attendancelog.FieldUserID)
	}
	if m.device_ip != nil {
		fields = append(fields, attendancelog.FieldDeviceIP)
	}
	if m.att_log != nil {
		fields = append(fields, attendancelog.FieldAttLog)
	}
	if m.status != nil {
		fields = append(fields, attendancelog.FieldStatus)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *AttendanceLogMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case attendancelog.FieldUserID:
		return m.UserID()
	case attendancelog.FieldDeviceIP:
		return m.DeviceIP()
	case attendancelog.FieldAttLog:
		return m.AttLog()
	case attendancelog.FieldStatus:
		return m.Status()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *AttendanceLogMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case attendancelog.FieldUserID:
		return m.OldUserID(ctx)
	case attendancelog.FieldDeviceIP:
		return m.OldDeviceIP(ctx)
	case attendancelog.FieldAttLog:
		return m.OldAttLog(ctx)
	case attendancelog.FieldStatus:
		return m.OldStatus(ctx)
	}
	return nil, fmt.Errorf("unknown AttendanceLog field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AttendanceLogMutation) SetField(name string, value ent.Value) error {
	switch name {
	case attendancelog.FieldUserID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUserID(v)
		return nil
	case attendancelog.FieldDeviceIP:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDeviceIP(v)
		return nil
	case attendancelog.FieldAttLog:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAttLog(v)
		return nil
	case attendancelog.FieldStatus:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	}
	return fmt.Errorf("unknown AttendanceLog field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *AttendanceLogMutation) AddedFields() []string {
	var fields []string
	if m.adduser_id != nil {
		fields = append(fields, attendancelog.FieldUserID)
	}
	if m.addstatus != nil {
		fields = append(fields, attendancelog.FieldStatus)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *AttendanceLogMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case attendancelog.FieldUserID:
		return m.AddedUserID()
	case attendancelog.FieldStatus:
		return m.AddedStatus()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AttendanceLogMutation) AddField(name string, value ent.Value) error {
	switch name {
	case attendancelog.FieldUserID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddUserID(v)
		return nil
	case attendancelog.FieldStatus:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddStatus(v)
		return nil
	}
	return fmt.Errorf("unknown AttendanceLog numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *AttendanceLogMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *AttendanceLogMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *AttendanceLogMutation) ClearField(name string) error {
	return fmt.Errorf("unknown AttendanceLog nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *AttendanceLogMutation) ResetField(name string) error {
	switch name {
	case attendancelog.FieldUserID:
		m.ResetUserID()
		return nil
	case attendancelog.FieldDeviceIP:
		m.ResetDeviceIP()
		return nil
	case attendancelog.FieldAttLog:
		m.ResetAttLog()
		return nil
	case attendancelog.FieldStatus:
		m.ResetStatus()
		return nil
	}
	return fmt.Errorf("unknown AttendanceLog field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *AttendanceLogMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *AttendanceLogMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *AttendanceLogMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *AttendanceLogMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *AttendanceLogMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *AttendanceLogMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *AttendanceLogMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown AttendanceLog unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *AttendanceLogMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown AttendanceLog edge %s", name)
}
