// Code generated by ent, DO NOT EDIT.

package perusahaan

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the perusahaan type in the database.
	Label = "perusahaan"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldUpdatedBy holds the string denoting the updated_by field in the database.
	FieldUpdatedBy = "updated_by"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldDeleteTime holds the string denoting the delete_time field in the database.
	FieldDeleteTime = "delete_time"
	// FieldKodePerusahaan holds the string denoting the kode_perusahaan field in the database.
	FieldKodePerusahaan = "kode_perusahaan"
	// FieldNamaPerusahaan holds the string denoting the nama_perusahaan field in the database.
	FieldNamaPerusahaan = "nama_perusahaan"
	// FieldKodeCabang holds the string denoting the kode_cabang field in the database.
	FieldKodeCabang = "kode_cabang"
	// FieldCabang holds the string denoting the cabang field in the database.
	FieldCabang = "cabang"
	// FieldAlamat holds the string denoting the alamat field in the database.
	FieldAlamat = "alamat"
	// FieldTelp holds the string denoting the telp field in the database.
	FieldTelp = "telp"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldLogo holds the string denoting the logo field in the database.
	FieldLogo = "logo"
	// Table holds the table name of the perusahaan in the database.
	Table = "perusahaans"
)

// Columns holds all SQL columns for perusahaan fields.
var Columns = []string{
	FieldID,
	FieldCreatedBy,
	FieldUpdatedBy,
	FieldCreateTime,
	FieldUpdateTime,
	FieldDeleteTime,
	FieldKodePerusahaan,
	FieldNamaPerusahaan,
	FieldKodeCabang,
	FieldCabang,
	FieldAlamat,
	FieldTelp,
	FieldEmail,
	FieldLogo,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// NamaPerusahaanValidator is a validator for the "nama_perusahaan" field. It is called by the builders before save.
	NamaPerusahaanValidator func(string) error
	// KodeCabangValidator is a validator for the "kode_cabang" field. It is called by the builders before save.
	KodeCabangValidator func(string) error
	// CabangValidator is a validator for the "cabang" field. It is called by the builders before save.
	CabangValidator func(string) error
)

// OrderOption defines the ordering options for the Perusahaan queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByUpdatedBy orders the results by the updated_by field.
func ByUpdatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedBy, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByDeleteTime orders the results by the delete_time field.
func ByDeleteTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeleteTime, opts...).ToFunc()
}

// ByKodePerusahaan orders the results by the kode_perusahaan field.
func ByKodePerusahaan(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKodePerusahaan, opts...).ToFunc()
}

// ByNamaPerusahaan orders the results by the nama_perusahaan field.
func ByNamaPerusahaan(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNamaPerusahaan, opts...).ToFunc()
}

// ByKodeCabang orders the results by the kode_cabang field.
func ByKodeCabang(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKodeCabang, opts...).ToFunc()
}

// ByCabang orders the results by the cabang field.
func ByCabang(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCabang, opts...).ToFunc()
}

// ByAlamat orders the results by the alamat field.
func ByAlamat(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAlamat, opts...).ToFunc()
}

// ByTelp orders the results by the telp field.
func ByTelp(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTelp, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByLogo orders the results by the logo field.
func ByLogo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLogo, opts...).ToFunc()
}
