// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AttendancesColumns holds the columns for the "attendances" table.
	AttendancesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "karyacode", Type: field.TypeString},
		{Name: "clock_in_time", Type: field.TypeTime},
		{Name: "clock_out_time", Type: field.TypeTime, Nullable: true},
		{Name: "status", Type: field.TypeString, Nullable: true, Size: 50},
		{Name: "effective_work_duration_minutes", Type: field.TypeInt, Nullable: true},
		{Name: "overtime_minutes", Type: field.TypeInt, Default: 0},
		{Name: "notes", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "location", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// AttendancesTable holds the schema information for the "attendances" table.
	AttendancesTable = &schema.Table{
		Name:       "attendances",
		Columns:    AttendancesColumns,
		PrimaryKey: []*schema.Column{AttendancesColumns[0]},
	}
	// EmployeeShiftSchedulesColumns holds the columns for the "employee_shift_schedules" table.
	EmployeeShiftSchedulesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "karyacode", Type: field.TypeString},
		{Name: "assignment_date", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// EmployeeShiftSchedulesTable holds the schema information for the "employee_shift_schedules" table.
	EmployeeShiftSchedulesTable = &schema.Table{
		Name:       "employee_shift_schedules",
		Columns:    EmployeeShiftSchedulesColumns,
		PrimaryKey: []*schema.Column{EmployeeShiftSchedulesColumns[0]},
	}
	// OvertimesColumns holds the columns for the "overtimes" table.
	OvertimesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "karyacode", Type: field.TypeString},
		{Name: "overtime_start_time", Type: field.TypeTime},
		{Name: "overtime_end_time", Type: field.TypeTime},
		{Name: "duration_minutes", Type: field.TypeInt},
		{Name: "approved_by", Type: field.TypeString},
		{Name: "status", Type: field.TypeString, Size: 50, Default: "pending"},
		{Name: "notes", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// OvertimesTable holds the schema information for the "overtimes" table.
	OvertimesTable = &schema.Table{
		Name:       "overtimes",
		Columns:    OvertimesColumns,
		PrimaryKey: []*schema.Column{OvertimesColumns[0]},
	}
	// ShiftsColumns holds the columns for the "shifts" table.
	ShiftsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true, Size: 100},
		{Name: "start_time", Type: field.TypeTime},
		{Name: "end_time", Type: field.TypeTime},
		{Name: "break_duration_minutes", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ShiftsTable holds the schema information for the "shifts" table.
	ShiftsTable = &schema.Table{
		Name:       "shifts",
		Columns:    ShiftsColumns,
		PrimaryKey: []*schema.Column{ShiftsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AttendancesTable,
		EmployeeShiftSchedulesTable,
		OvertimesTable,
		ShiftsTable,
	}
)

func init() {
}
