// Code generated by ent, DO NOT EDIT.

package shiftschedule

import (
	"mall-go/module/shiftschedule/service/internal/data/model/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldLTE(FieldID, id))
}

// ScheduleCode applies equality check predicate on the "schedule_code" field. It's identical to ScheduleCodeEQ.
func ScheduleCode(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldEQ(FieldScheduleCode, v))
}

// KaryaCode applies equality check predicate on the "karya_code" field. It's identical to KaryaCodeEQ.
func KaryaCode(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldEQ(FieldKaryaCode, v))
}

// Tanggal applies equality check predicate on the "tanggal" field. It's identical to TanggalEQ.
func Tanggal(v time.Time) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldEQ(FieldTanggal, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldEQ(FieldCreatedBy, v))
}

// DepartCode applies equality check predicate on the "depart_code" field. It's identical to DepartCodeEQ.
func DepartCode(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldEQ(FieldDepartCode, v))
}

// ShiftID applies equality check predicate on the "shift_id" field. It's identical to ShiftIDEQ.
func ShiftID(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldEQ(FieldShiftID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldEQ(FieldUpdatedAt, v))
}

// ScheduleCodeEQ applies the EQ predicate on the "schedule_code" field.
func ScheduleCodeEQ(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldEQ(FieldScheduleCode, v))
}

// ScheduleCodeNEQ applies the NEQ predicate on the "schedule_code" field.
func ScheduleCodeNEQ(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldNEQ(FieldScheduleCode, v))
}

// ScheduleCodeIn applies the In predicate on the "schedule_code" field.
func ScheduleCodeIn(vs ...string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldIn(FieldScheduleCode, vs...))
}

// ScheduleCodeNotIn applies the NotIn predicate on the "schedule_code" field.
func ScheduleCodeNotIn(vs ...string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldNotIn(FieldScheduleCode, vs...))
}

// ScheduleCodeGT applies the GT predicate on the "schedule_code" field.
func ScheduleCodeGT(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldGT(FieldScheduleCode, v))
}

// ScheduleCodeGTE applies the GTE predicate on the "schedule_code" field.
func ScheduleCodeGTE(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldGTE(FieldScheduleCode, v))
}

// ScheduleCodeLT applies the LT predicate on the "schedule_code" field.
func ScheduleCodeLT(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldLT(FieldScheduleCode, v))
}

// ScheduleCodeLTE applies the LTE predicate on the "schedule_code" field.
func ScheduleCodeLTE(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldLTE(FieldScheduleCode, v))
}

// ScheduleCodeContains applies the Contains predicate on the "schedule_code" field.
func ScheduleCodeContains(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldContains(FieldScheduleCode, v))
}

// ScheduleCodeHasPrefix applies the HasPrefix predicate on the "schedule_code" field.
func ScheduleCodeHasPrefix(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldHasPrefix(FieldScheduleCode, v))
}

// ScheduleCodeHasSuffix applies the HasSuffix predicate on the "schedule_code" field.
func ScheduleCodeHasSuffix(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldHasSuffix(FieldScheduleCode, v))
}

// ScheduleCodeEqualFold applies the EqualFold predicate on the "schedule_code" field.
func ScheduleCodeEqualFold(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldEqualFold(FieldScheduleCode, v))
}

// ScheduleCodeContainsFold applies the ContainsFold predicate on the "schedule_code" field.
func ScheduleCodeContainsFold(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldContainsFold(FieldScheduleCode, v))
}

// KaryaCodeEQ applies the EQ predicate on the "karya_code" field.
func KaryaCodeEQ(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldEQ(FieldKaryaCode, v))
}

// KaryaCodeNEQ applies the NEQ predicate on the "karya_code" field.
func KaryaCodeNEQ(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldNEQ(FieldKaryaCode, v))
}

// KaryaCodeIn applies the In predicate on the "karya_code" field.
func KaryaCodeIn(vs ...string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldIn(FieldKaryaCode, vs...))
}

// KaryaCodeNotIn applies the NotIn predicate on the "karya_code" field.
func KaryaCodeNotIn(vs ...string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldNotIn(FieldKaryaCode, vs...))
}

// KaryaCodeGT applies the GT predicate on the "karya_code" field.
func KaryaCodeGT(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldGT(FieldKaryaCode, v))
}

// KaryaCodeGTE applies the GTE predicate on the "karya_code" field.
func KaryaCodeGTE(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldGTE(FieldKaryaCode, v))
}

// KaryaCodeLT applies the LT predicate on the "karya_code" field.
func KaryaCodeLT(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldLT(FieldKaryaCode, v))
}

// KaryaCodeLTE applies the LTE predicate on the "karya_code" field.
func KaryaCodeLTE(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldLTE(FieldKaryaCode, v))
}

// KaryaCodeContains applies the Contains predicate on the "karya_code" field.
func KaryaCodeContains(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldContains(FieldKaryaCode, v))
}

// KaryaCodeHasPrefix applies the HasPrefix predicate on the "karya_code" field.
func KaryaCodeHasPrefix(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldHasPrefix(FieldKaryaCode, v))
}

// KaryaCodeHasSuffix applies the HasSuffix predicate on the "karya_code" field.
func KaryaCodeHasSuffix(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldHasSuffix(FieldKaryaCode, v))
}

// KaryaCodeEqualFold applies the EqualFold predicate on the "karya_code" field.
func KaryaCodeEqualFold(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldEqualFold(FieldKaryaCode, v))
}

// KaryaCodeContainsFold applies the ContainsFold predicate on the "karya_code" field.
func KaryaCodeContainsFold(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldContainsFold(FieldKaryaCode, v))
}

// TanggalEQ applies the EQ predicate on the "tanggal" field.
func TanggalEQ(v time.Time) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldEQ(FieldTanggal, v))
}

// TanggalNEQ applies the NEQ predicate on the "tanggal" field.
func TanggalNEQ(v time.Time) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldNEQ(FieldTanggal, v))
}

// TanggalIn applies the In predicate on the "tanggal" field.
func TanggalIn(vs ...time.Time) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldIn(FieldTanggal, vs...))
}

// TanggalNotIn applies the NotIn predicate on the "tanggal" field.
func TanggalNotIn(vs ...time.Time) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldNotIn(FieldTanggal, vs...))
}

// TanggalGT applies the GT predicate on the "tanggal" field.
func TanggalGT(v time.Time) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldGT(FieldTanggal, v))
}

// TanggalGTE applies the GTE predicate on the "tanggal" field.
func TanggalGTE(v time.Time) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldGTE(FieldTanggal, v))
}

// TanggalLT applies the LT predicate on the "tanggal" field.
func TanggalLT(v time.Time) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldLT(FieldTanggal, v))
}

// TanggalLTE applies the LTE predicate on the "tanggal" field.
func TanggalLTE(v time.Time) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldLTE(FieldTanggal, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldContainsFold(FieldCreatedBy, v))
}

// DepartCodeEQ applies the EQ predicate on the "depart_code" field.
func DepartCodeEQ(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldEQ(FieldDepartCode, v))
}

// DepartCodeNEQ applies the NEQ predicate on the "depart_code" field.
func DepartCodeNEQ(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldNEQ(FieldDepartCode, v))
}

// DepartCodeIn applies the In predicate on the "depart_code" field.
func DepartCodeIn(vs ...string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldIn(FieldDepartCode, vs...))
}

// DepartCodeNotIn applies the NotIn predicate on the "depart_code" field.
func DepartCodeNotIn(vs ...string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldNotIn(FieldDepartCode, vs...))
}

// DepartCodeGT applies the GT predicate on the "depart_code" field.
func DepartCodeGT(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldGT(FieldDepartCode, v))
}

// DepartCodeGTE applies the GTE predicate on the "depart_code" field.
func DepartCodeGTE(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldGTE(FieldDepartCode, v))
}

// DepartCodeLT applies the LT predicate on the "depart_code" field.
func DepartCodeLT(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldLT(FieldDepartCode, v))
}

// DepartCodeLTE applies the LTE predicate on the "depart_code" field.
func DepartCodeLTE(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldLTE(FieldDepartCode, v))
}

// DepartCodeContains applies the Contains predicate on the "depart_code" field.
func DepartCodeContains(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldContains(FieldDepartCode, v))
}

// DepartCodeHasPrefix applies the HasPrefix predicate on the "depart_code" field.
func DepartCodeHasPrefix(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldHasPrefix(FieldDepartCode, v))
}

// DepartCodeHasSuffix applies the HasSuffix predicate on the "depart_code" field.
func DepartCodeHasSuffix(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldHasSuffix(FieldDepartCode, v))
}

// DepartCodeEqualFold applies the EqualFold predicate on the "depart_code" field.
func DepartCodeEqualFold(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldEqualFold(FieldDepartCode, v))
}

// DepartCodeContainsFold applies the ContainsFold predicate on the "depart_code" field.
func DepartCodeContainsFold(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldContainsFold(FieldDepartCode, v))
}

// ShiftIDEQ applies the EQ predicate on the "shift_id" field.
func ShiftIDEQ(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldEQ(FieldShiftID, v))
}

// ShiftIDNEQ applies the NEQ predicate on the "shift_id" field.
func ShiftIDNEQ(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldNEQ(FieldShiftID, v))
}

// ShiftIDIn applies the In predicate on the "shift_id" field.
func ShiftIDIn(vs ...string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldIn(FieldShiftID, vs...))
}

// ShiftIDNotIn applies the NotIn predicate on the "shift_id" field.
func ShiftIDNotIn(vs ...string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldNotIn(FieldShiftID, vs...))
}

// ShiftIDGT applies the GT predicate on the "shift_id" field.
func ShiftIDGT(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldGT(FieldShiftID, v))
}

// ShiftIDGTE applies the GTE predicate on the "shift_id" field.
func ShiftIDGTE(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldGTE(FieldShiftID, v))
}

// ShiftIDLT applies the LT predicate on the "shift_id" field.
func ShiftIDLT(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldLT(FieldShiftID, v))
}

// ShiftIDLTE applies the LTE predicate on the "shift_id" field.
func ShiftIDLTE(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldLTE(FieldShiftID, v))
}

// ShiftIDContains applies the Contains predicate on the "shift_id" field.
func ShiftIDContains(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldContains(FieldShiftID, v))
}

// ShiftIDHasPrefix applies the HasPrefix predicate on the "shift_id" field.
func ShiftIDHasPrefix(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldHasPrefix(FieldShiftID, v))
}

// ShiftIDHasSuffix applies the HasSuffix predicate on the "shift_id" field.
func ShiftIDHasSuffix(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldHasSuffix(FieldShiftID, v))
}

// ShiftIDEqualFold applies the EqualFold predicate on the "shift_id" field.
func ShiftIDEqualFold(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldEqualFold(FieldShiftID, v))
}

// ShiftIDContainsFold applies the ContainsFold predicate on the "shift_id" field.
func ShiftIDContainsFold(v string) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldContainsFold(FieldShiftID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ShiftSchedule) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ShiftSchedule) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ShiftSchedule) predicate.ShiftSchedule {
	return predicate.ShiftSchedule(sql.NotPredicates(p))
}
