// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/attendance-report/service/v1/attendance-report.proto

package v1

import (
	_ "github.com/google/gnostic/openapiv3"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DepartmentCode string                 `protobuf:"bytes,1,opt,name=department_code,json=departmentCode,proto3" json:"department_code,omitempty"`
	StartDate      string                 `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // format: YYYY-MM-DD
	EndDate        string                 `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GenerateRequest) Reset() {
	*x = GenerateRequest{}
	mi := &file_api_attendance_report_service_v1_attendance_report_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRequest) ProtoMessage() {}

func (x *GenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_attendance_report_service_v1_attendance_report_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRequest.ProtoReflect.Descriptor instead.
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return file_api_attendance_report_service_v1_attendance_report_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateRequest) GetDepartmentCode() string {
	if x != nil {
		return x.DepartmentCode
	}
	return ""
}

func (x *GenerateRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GenerateRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type GenerateReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PdfUrl        string                 `protobuf:"bytes,1,opt,name=pdf_url,json=pdfUrl,proto3" json:"pdf_url,omitempty"` // PDF link dari Minio / CDN
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateReply) Reset() {
	*x = GenerateReply{}
	mi := &file_api_attendance_report_service_v1_attendance_report_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateReply) ProtoMessage() {}

func (x *GenerateReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_attendance_report_service_v1_attendance_report_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateReply.ProtoReflect.Descriptor instead.
func (*GenerateReply) Descriptor() ([]byte, []int) {
	return file_api_attendance_report_service_v1_attendance_report_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateReply) GetPdfUrl() string {
	if x != nil {
		return x.PdfUrl
	}
	return ""
}

var File_api_attendance_report_service_v1_attendance_report_proto protoreflect.FileDescriptor

const file_api_attendance_report_service_v1_attendance_report_proto_rawDesc = "" +
	"\n" +
	"8api/attendance-report/service/v1/attendance-report.proto\x12\x14attendance_report.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bopenapiv3/annotations.proto\"t\n" +
	"\x0fGenerateRequest\x12'\n" +
	"\x0fdepartment_code\x18\x01 \x01(\tR\x0edepartmentCode\x12\x1d\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x03 \x01(\tR\aendDate\"(\n" +
	"\rGenerateReply\x12\x17\n" +
	"\apdf_url\x18\x01 \x01(\tR\x06pdfUrl2}\n" +
	"\rReportService\x12l\n" +
	"\x1eGenerateDepartmentHistoryClock\x12%.attendance_report.v1.GenerateRequest\x1a#.attendance_report.v1.GenerateReplyB\xae\x01\xbaGv\x12t\n" +
	"\x19attendance_report service\x12\x19attendance_report service\"5\n" +
	"\x06fuadhs\x12\x15http://localhost:8001\x1a\x14fuadhasan2@gmail.com2\x050.0.1\n" +
	"\x14attendance_report.v1P\x01Z\x1bapi/attendance_report/v1;v1b\x06proto3"

var (
	file_api_attendance_report_service_v1_attendance_report_proto_rawDescOnce sync.Once
	file_api_attendance_report_service_v1_attendance_report_proto_rawDescData []byte
)

func file_api_attendance_report_service_v1_attendance_report_proto_rawDescGZIP() []byte {
	file_api_attendance_report_service_v1_attendance_report_proto_rawDescOnce.Do(func() {
		file_api_attendance_report_service_v1_attendance_report_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_attendance_report_service_v1_attendance_report_proto_rawDesc), len(file_api_attendance_report_service_v1_attendance_report_proto_rawDesc)))
	})
	return file_api_attendance_report_service_v1_attendance_report_proto_rawDescData
}

var file_api_attendance_report_service_v1_attendance_report_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_attendance_report_service_v1_attendance_report_proto_goTypes = []any{
	(*GenerateRequest)(nil), // 0: attendance_report.v1.GenerateRequest
	(*GenerateReply)(nil),   // 1: attendance_report.v1.GenerateReply
}
var file_api_attendance_report_service_v1_attendance_report_proto_depIdxs = []int32{
	0, // 0: attendance_report.v1.ReportService.GenerateDepartmentHistoryClock:input_type -> attendance_report.v1.GenerateRequest
	1, // 1: attendance_report.v1.ReportService.GenerateDepartmentHistoryClock:output_type -> attendance_report.v1.GenerateReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_attendance_report_service_v1_attendance_report_proto_init() }
func file_api_attendance_report_service_v1_attendance_report_proto_init() {
	if File_api_attendance_report_service_v1_attendance_report_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_attendance_report_service_v1_attendance_report_proto_rawDesc), len(file_api_attendance_report_service_v1_attendance_report_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_attendance_report_service_v1_attendance_report_proto_goTypes,
		DependencyIndexes: file_api_attendance_report_service_v1_attendance_report_proto_depIdxs,
		MessageInfos:      file_api_attendance_report_service_v1_attendance_report_proto_msgTypes,
	}.Build()
	File_api_attendance_report_service_v1_attendance_report_proto = out.File
	file_api_attendance_report_service_v1_attendance_report_proto_goTypes = nil
	file_api_attendance_report_service_v1_attendance_report_proto_depIdxs = nil
}
