// Code generated by ent, DO NOT EDIT.

package position

import (
	"mall-go/module/organization/service/internal/data/model/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Position {
	return predicate.Position(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Position {
	return predicate.Position(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Position {
	return predicate.Position(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Position {
	return predicate.Position(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Position {
	return predicate.Position(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Position {
	return predicate.Position(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Position {
	return predicate.Position(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Position {
	return predicate.Position(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Position {
	return predicate.Position(sql.FieldLTE(FieldID, id))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.Position {
	return predicate.Position(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v string) predicate.Position {
	return predicate.Position(sql.FieldEQ(FieldUpdatedBy, v))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.Position {
	return predicate.Position(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.Position {
	return predicate.Position(sql.FieldEQ(FieldUpdateTime, v))
}

// DeleteTime applies equality check predicate on the "delete_time" field. It's identical to DeleteTimeEQ.
func DeleteTime(v time.Time) predicate.Position {
	return predicate.Position(sql.FieldEQ(FieldDeleteTime, v))
}

// PositionCode applies equality check predicate on the "position_code" field. It's identical to PositionCodeEQ.
func PositionCode(v string) predicate.Position {
	return predicate.Position(sql.FieldEQ(FieldPositionCode, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Position {
	return predicate.Position(sql.FieldEQ(FieldName, v))
}

// RoleName applies equality check predicate on the "role_name" field. It's identical to RoleNameEQ.
func RoleName(v string) predicate.Position {
	return predicate.Position(sql.FieldEQ(FieldRoleName, v))
}

// DepartmentCode applies equality check predicate on the "department_code" field. It's identical to DepartmentCodeEQ.
func DepartmentCode(v string) predicate.Position {
	return predicate.Position(sql.FieldEQ(FieldDepartmentCode, v))
}

// ReportsToPositionID applies equality check predicate on the "reports_to_position_id" field. It's identical to ReportsToPositionIDEQ.
func ReportsToPositionID(v string) predicate.Position {
	return predicate.Position(sql.FieldEQ(FieldReportsToPositionID, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.Position {
	return predicate.Position(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.Position {
	return predicate.Position(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.Position {
	return predicate.Position(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.Position {
	return predicate.Position(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.Position {
	return predicate.Position(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.Position {
	return predicate.Position(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.Position {
	return predicate.Position(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.Position {
	return predicate.Position(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.Position {
	return predicate.Position(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.Position {
	return predicate.Position(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.Position {
	return predicate.Position(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.Position {
	return predicate.Position(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.Position {
	return predicate.Position(sql.FieldNotNull(FieldCreatedBy))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.Position {
	return predicate.Position(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.Position {
	return predicate.Position(sql.FieldContainsFold(FieldCreatedBy, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v string) predicate.Position {
	return predicate.Position(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v string) predicate.Position {
	return predicate.Position(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...string) predicate.Position {
	return predicate.Position(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...string) predicate.Position {
	return predicate.Position(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v string) predicate.Position {
	return predicate.Position(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v string) predicate.Position {
	return predicate.Position(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v string) predicate.Position {
	return predicate.Position(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v string) predicate.Position {
	return predicate.Position(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByContains applies the Contains predicate on the "updated_by" field.
func UpdatedByContains(v string) predicate.Position {
	return predicate.Position(sql.FieldContains(FieldUpdatedBy, v))
}

// UpdatedByHasPrefix applies the HasPrefix predicate on the "updated_by" field.
func UpdatedByHasPrefix(v string) predicate.Position {
	return predicate.Position(sql.FieldHasPrefix(FieldUpdatedBy, v))
}

// UpdatedByHasSuffix applies the HasSuffix predicate on the "updated_by" field.
func UpdatedByHasSuffix(v string) predicate.Position {
	return predicate.Position(sql.FieldHasSuffix(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.Position {
	return predicate.Position(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.Position {
	return predicate.Position(sql.FieldNotNull(FieldUpdatedBy))
}

// UpdatedByEqualFold applies the EqualFold predicate on the "updated_by" field.
func UpdatedByEqualFold(v string) predicate.Position {
	return predicate.Position(sql.FieldEqualFold(FieldUpdatedBy, v))
}

// UpdatedByContainsFold applies the ContainsFold predicate on the "updated_by" field.
func UpdatedByContainsFold(v string) predicate.Position {
	return predicate.Position(sql.FieldContainsFold(FieldUpdatedBy, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.Position {
	return predicate.Position(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.Position {
	return predicate.Position(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.Position {
	return predicate.Position(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.Position {
	return predicate.Position(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.Position {
	return predicate.Position(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.Position {
	return predicate.Position(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.Position {
	return predicate.Position(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.Position {
	return predicate.Position(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.Position {
	return predicate.Position(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.Position {
	return predicate.Position(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.Position {
	return predicate.Position(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.Position {
	return predicate.Position(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.Position {
	return predicate.Position(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.Position {
	return predicate.Position(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.Position {
	return predicate.Position(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.Position {
	return predicate.Position(sql.FieldLTE(FieldUpdateTime, v))
}

// DeleteTimeEQ applies the EQ predicate on the "delete_time" field.
func DeleteTimeEQ(v time.Time) predicate.Position {
	return predicate.Position(sql.FieldEQ(FieldDeleteTime, v))
}

// DeleteTimeNEQ applies the NEQ predicate on the "delete_time" field.
func DeleteTimeNEQ(v time.Time) predicate.Position {
	return predicate.Position(sql.FieldNEQ(FieldDeleteTime, v))
}

// DeleteTimeIn applies the In predicate on the "delete_time" field.
func DeleteTimeIn(vs ...time.Time) predicate.Position {
	return predicate.Position(sql.FieldIn(FieldDeleteTime, vs...))
}

// DeleteTimeNotIn applies the NotIn predicate on the "delete_time" field.
func DeleteTimeNotIn(vs ...time.Time) predicate.Position {
	return predicate.Position(sql.FieldNotIn(FieldDeleteTime, vs...))
}

// DeleteTimeGT applies the GT predicate on the "delete_time" field.
func DeleteTimeGT(v time.Time) predicate.Position {
	return predicate.Position(sql.FieldGT(FieldDeleteTime, v))
}

// DeleteTimeGTE applies the GTE predicate on the "delete_time" field.
func DeleteTimeGTE(v time.Time) predicate.Position {
	return predicate.Position(sql.FieldGTE(FieldDeleteTime, v))
}

// DeleteTimeLT applies the LT predicate on the "delete_time" field.
func DeleteTimeLT(v time.Time) predicate.Position {
	return predicate.Position(sql.FieldLT(FieldDeleteTime, v))
}

// DeleteTimeLTE applies the LTE predicate on the "delete_time" field.
func DeleteTimeLTE(v time.Time) predicate.Position {
	return predicate.Position(sql.FieldLTE(FieldDeleteTime, v))
}

// DeleteTimeIsNil applies the IsNil predicate on the "delete_time" field.
func DeleteTimeIsNil() predicate.Position {
	return predicate.Position(sql.FieldIsNull(FieldDeleteTime))
}

// DeleteTimeNotNil applies the NotNil predicate on the "delete_time" field.
func DeleteTimeNotNil() predicate.Position {
	return predicate.Position(sql.FieldNotNull(FieldDeleteTime))
}

// PositionCodeEQ applies the EQ predicate on the "position_code" field.
func PositionCodeEQ(v string) predicate.Position {
	return predicate.Position(sql.FieldEQ(FieldPositionCode, v))
}

// PositionCodeNEQ applies the NEQ predicate on the "position_code" field.
func PositionCodeNEQ(v string) predicate.Position {
	return predicate.Position(sql.FieldNEQ(FieldPositionCode, v))
}

// PositionCodeIn applies the In predicate on the "position_code" field.
func PositionCodeIn(vs ...string) predicate.Position {
	return predicate.Position(sql.FieldIn(FieldPositionCode, vs...))
}

// PositionCodeNotIn applies the NotIn predicate on the "position_code" field.
func PositionCodeNotIn(vs ...string) predicate.Position {
	return predicate.Position(sql.FieldNotIn(FieldPositionCode, vs...))
}

// PositionCodeGT applies the GT predicate on the "position_code" field.
func PositionCodeGT(v string) predicate.Position {
	return predicate.Position(sql.FieldGT(FieldPositionCode, v))
}

// PositionCodeGTE applies the GTE predicate on the "position_code" field.
func PositionCodeGTE(v string) predicate.Position {
	return predicate.Position(sql.FieldGTE(FieldPositionCode, v))
}

// PositionCodeLT applies the LT predicate on the "position_code" field.
func PositionCodeLT(v string) predicate.Position {
	return predicate.Position(sql.FieldLT(FieldPositionCode, v))
}

// PositionCodeLTE applies the LTE predicate on the "position_code" field.
func PositionCodeLTE(v string) predicate.Position {
	return predicate.Position(sql.FieldLTE(FieldPositionCode, v))
}

// PositionCodeContains applies the Contains predicate on the "position_code" field.
func PositionCodeContains(v string) predicate.Position {
	return predicate.Position(sql.FieldContains(FieldPositionCode, v))
}

// PositionCodeHasPrefix applies the HasPrefix predicate on the "position_code" field.
func PositionCodeHasPrefix(v string) predicate.Position {
	return predicate.Position(sql.FieldHasPrefix(FieldPositionCode, v))
}

// PositionCodeHasSuffix applies the HasSuffix predicate on the "position_code" field.
func PositionCodeHasSuffix(v string) predicate.Position {
	return predicate.Position(sql.FieldHasSuffix(FieldPositionCode, v))
}

// PositionCodeEqualFold applies the EqualFold predicate on the "position_code" field.
func PositionCodeEqualFold(v string) predicate.Position {
	return predicate.Position(sql.FieldEqualFold(FieldPositionCode, v))
}

// PositionCodeContainsFold applies the ContainsFold predicate on the "position_code" field.
func PositionCodeContainsFold(v string) predicate.Position {
	return predicate.Position(sql.FieldContainsFold(FieldPositionCode, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Position {
	return predicate.Position(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Position {
	return predicate.Position(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Position {
	return predicate.Position(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Position {
	return predicate.Position(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Position {
	return predicate.Position(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Position {
	return predicate.Position(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Position {
	return predicate.Position(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Position {
	return predicate.Position(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Position {
	return predicate.Position(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Position {
	return predicate.Position(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Position {
	return predicate.Position(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Position {
	return predicate.Position(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Position {
	return predicate.Position(sql.FieldContainsFold(FieldName, v))
}

// RoleNameEQ applies the EQ predicate on the "role_name" field.
func RoleNameEQ(v string) predicate.Position {
	return predicate.Position(sql.FieldEQ(FieldRoleName, v))
}

// RoleNameNEQ applies the NEQ predicate on the "role_name" field.
func RoleNameNEQ(v string) predicate.Position {
	return predicate.Position(sql.FieldNEQ(FieldRoleName, v))
}

// RoleNameIn applies the In predicate on the "role_name" field.
func RoleNameIn(vs ...string) predicate.Position {
	return predicate.Position(sql.FieldIn(FieldRoleName, vs...))
}

// RoleNameNotIn applies the NotIn predicate on the "role_name" field.
func RoleNameNotIn(vs ...string) predicate.Position {
	return predicate.Position(sql.FieldNotIn(FieldRoleName, vs...))
}

// RoleNameGT applies the GT predicate on the "role_name" field.
func RoleNameGT(v string) predicate.Position {
	return predicate.Position(sql.FieldGT(FieldRoleName, v))
}

// RoleNameGTE applies the GTE predicate on the "role_name" field.
func RoleNameGTE(v string) predicate.Position {
	return predicate.Position(sql.FieldGTE(FieldRoleName, v))
}

// RoleNameLT applies the LT predicate on the "role_name" field.
func RoleNameLT(v string) predicate.Position {
	return predicate.Position(sql.FieldLT(FieldRoleName, v))
}

// RoleNameLTE applies the LTE predicate on the "role_name" field.
func RoleNameLTE(v string) predicate.Position {
	return predicate.Position(sql.FieldLTE(FieldRoleName, v))
}

// RoleNameContains applies the Contains predicate on the "role_name" field.
func RoleNameContains(v string) predicate.Position {
	return predicate.Position(sql.FieldContains(FieldRoleName, v))
}

// RoleNameHasPrefix applies the HasPrefix predicate on the "role_name" field.
func RoleNameHasPrefix(v string) predicate.Position {
	return predicate.Position(sql.FieldHasPrefix(FieldRoleName, v))
}

// RoleNameHasSuffix applies the HasSuffix predicate on the "role_name" field.
func RoleNameHasSuffix(v string) predicate.Position {
	return predicate.Position(sql.FieldHasSuffix(FieldRoleName, v))
}

// RoleNameEqualFold applies the EqualFold predicate on the "role_name" field.
func RoleNameEqualFold(v string) predicate.Position {
	return predicate.Position(sql.FieldEqualFold(FieldRoleName, v))
}

// RoleNameContainsFold applies the ContainsFold predicate on the "role_name" field.
func RoleNameContainsFold(v string) predicate.Position {
	return predicate.Position(sql.FieldContainsFold(FieldRoleName, v))
}

// DepartmentCodeEQ applies the EQ predicate on the "department_code" field.
func DepartmentCodeEQ(v string) predicate.Position {
	return predicate.Position(sql.FieldEQ(FieldDepartmentCode, v))
}

// DepartmentCodeNEQ applies the NEQ predicate on the "department_code" field.
func DepartmentCodeNEQ(v string) predicate.Position {
	return predicate.Position(sql.FieldNEQ(FieldDepartmentCode, v))
}

// DepartmentCodeIn applies the In predicate on the "department_code" field.
func DepartmentCodeIn(vs ...string) predicate.Position {
	return predicate.Position(sql.FieldIn(FieldDepartmentCode, vs...))
}

// DepartmentCodeNotIn applies the NotIn predicate on the "department_code" field.
func DepartmentCodeNotIn(vs ...string) predicate.Position {
	return predicate.Position(sql.FieldNotIn(FieldDepartmentCode, vs...))
}

// DepartmentCodeGT applies the GT predicate on the "department_code" field.
func DepartmentCodeGT(v string) predicate.Position {
	return predicate.Position(sql.FieldGT(FieldDepartmentCode, v))
}

// DepartmentCodeGTE applies the GTE predicate on the "department_code" field.
func DepartmentCodeGTE(v string) predicate.Position {
	return predicate.Position(sql.FieldGTE(FieldDepartmentCode, v))
}

// DepartmentCodeLT applies the LT predicate on the "department_code" field.
func DepartmentCodeLT(v string) predicate.Position {
	return predicate.Position(sql.FieldLT(FieldDepartmentCode, v))
}

// DepartmentCodeLTE applies the LTE predicate on the "department_code" field.
func DepartmentCodeLTE(v string) predicate.Position {
	return predicate.Position(sql.FieldLTE(FieldDepartmentCode, v))
}

// DepartmentCodeContains applies the Contains predicate on the "department_code" field.
func DepartmentCodeContains(v string) predicate.Position {
	return predicate.Position(sql.FieldContains(FieldDepartmentCode, v))
}

// DepartmentCodeHasPrefix applies the HasPrefix predicate on the "department_code" field.
func DepartmentCodeHasPrefix(v string) predicate.Position {
	return predicate.Position(sql.FieldHasPrefix(FieldDepartmentCode, v))
}

// DepartmentCodeHasSuffix applies the HasSuffix predicate on the "department_code" field.
func DepartmentCodeHasSuffix(v string) predicate.Position {
	return predicate.Position(sql.FieldHasSuffix(FieldDepartmentCode, v))
}

// DepartmentCodeIsNil applies the IsNil predicate on the "department_code" field.
func DepartmentCodeIsNil() predicate.Position {
	return predicate.Position(sql.FieldIsNull(FieldDepartmentCode))
}

// DepartmentCodeNotNil applies the NotNil predicate on the "department_code" field.
func DepartmentCodeNotNil() predicate.Position {
	return predicate.Position(sql.FieldNotNull(FieldDepartmentCode))
}

// DepartmentCodeEqualFold applies the EqualFold predicate on the "department_code" field.
func DepartmentCodeEqualFold(v string) predicate.Position {
	return predicate.Position(sql.FieldEqualFold(FieldDepartmentCode, v))
}

// DepartmentCodeContainsFold applies the ContainsFold predicate on the "department_code" field.
func DepartmentCodeContainsFold(v string) predicate.Position {
	return predicate.Position(sql.FieldContainsFold(FieldDepartmentCode, v))
}

// ReportsToPositionIDEQ applies the EQ predicate on the "reports_to_position_id" field.
func ReportsToPositionIDEQ(v string) predicate.Position {
	return predicate.Position(sql.FieldEQ(FieldReportsToPositionID, v))
}

// ReportsToPositionIDNEQ applies the NEQ predicate on the "reports_to_position_id" field.
func ReportsToPositionIDNEQ(v string) predicate.Position {
	return predicate.Position(sql.FieldNEQ(FieldReportsToPositionID, v))
}

// ReportsToPositionIDIn applies the In predicate on the "reports_to_position_id" field.
func ReportsToPositionIDIn(vs ...string) predicate.Position {
	return predicate.Position(sql.FieldIn(FieldReportsToPositionID, vs...))
}

// ReportsToPositionIDNotIn applies the NotIn predicate on the "reports_to_position_id" field.
func ReportsToPositionIDNotIn(vs ...string) predicate.Position {
	return predicate.Position(sql.FieldNotIn(FieldReportsToPositionID, vs...))
}

// ReportsToPositionIDGT applies the GT predicate on the "reports_to_position_id" field.
func ReportsToPositionIDGT(v string) predicate.Position {
	return predicate.Position(sql.FieldGT(FieldReportsToPositionID, v))
}

// ReportsToPositionIDGTE applies the GTE predicate on the "reports_to_position_id" field.
func ReportsToPositionIDGTE(v string) predicate.Position {
	return predicate.Position(sql.FieldGTE(FieldReportsToPositionID, v))
}

// ReportsToPositionIDLT applies the LT predicate on the "reports_to_position_id" field.
func ReportsToPositionIDLT(v string) predicate.Position {
	return predicate.Position(sql.FieldLT(FieldReportsToPositionID, v))
}

// ReportsToPositionIDLTE applies the LTE predicate on the "reports_to_position_id" field.
func ReportsToPositionIDLTE(v string) predicate.Position {
	return predicate.Position(sql.FieldLTE(FieldReportsToPositionID, v))
}

// ReportsToPositionIDContains applies the Contains predicate on the "reports_to_position_id" field.
func ReportsToPositionIDContains(v string) predicate.Position {
	return predicate.Position(sql.FieldContains(FieldReportsToPositionID, v))
}

// ReportsToPositionIDHasPrefix applies the HasPrefix predicate on the "reports_to_position_id" field.
func ReportsToPositionIDHasPrefix(v string) predicate.Position {
	return predicate.Position(sql.FieldHasPrefix(FieldReportsToPositionID, v))
}

// ReportsToPositionIDHasSuffix applies the HasSuffix predicate on the "reports_to_position_id" field.
func ReportsToPositionIDHasSuffix(v string) predicate.Position {
	return predicate.Position(sql.FieldHasSuffix(FieldReportsToPositionID, v))
}

// ReportsToPositionIDIsNil applies the IsNil predicate on the "reports_to_position_id" field.
func ReportsToPositionIDIsNil() predicate.Position {
	return predicate.Position(sql.FieldIsNull(FieldReportsToPositionID))
}

// ReportsToPositionIDNotNil applies the NotNil predicate on the "reports_to_position_id" field.
func ReportsToPositionIDNotNil() predicate.Position {
	return predicate.Position(sql.FieldNotNull(FieldReportsToPositionID))
}

// ReportsToPositionIDEqualFold applies the EqualFold predicate on the "reports_to_position_id" field.
func ReportsToPositionIDEqualFold(v string) predicate.Position {
	return predicate.Position(sql.FieldEqualFold(FieldReportsToPositionID, v))
}

// ReportsToPositionIDContainsFold applies the ContainsFold predicate on the "reports_to_position_id" field.
func ReportsToPositionIDContainsFold(v string) predicate.Position {
	return predicate.Position(sql.FieldContainsFold(FieldReportsToPositionID, v))
}

// HasAssignments applies the HasEdge predicate on the "assignments" edge.
func HasAssignments() predicate.Position {
	return predicate.Position(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AssignmentsTable, AssignmentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAssignmentsWith applies the HasEdge predicate on the "assignments" edge with a given conditions (other predicates).
func HasAssignmentsWith(preds ...predicate.Assignment) predicate.Position {
	return predicate.Position(func(s *sql.Selector) {
		step := newAssignmentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Position) predicate.Position {
	return predicate.Position(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Position) predicate.Position {
	return predicate.Position(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Position) predicate.Position {
	return predicate.Position(sql.NotPredicates(p))
}
