// Code generated by ent, DO NOT EDIT.

package model

import (
	"context"
	"errors"
	"fmt"
	"mall-go/module/employers/service/internal/data/model/employers"
	"mall-go/module/employers/service/internal/data/model/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EmployersUpdate is the builder for updating Employers entities.
type EmployersUpdate struct {
	config
	hooks    []Hook
	mutation *EmployersMutation
}

// Where appends a list predicates to the EmployersUpdate builder.
func (eu *EmployersUpdate) Where(ps ...predicate.Employers) *EmployersUpdate {
	eu.mutation.Where(ps...)
	return eu
}

// SetUpdateTime sets the "update_time" field.
func (eu *EmployersUpdate) SetUpdateTime(t time.Time) *EmployersUpdate {
	eu.mutation.SetUpdateTime(t)
	return eu
}

// SetDeleteTime sets the "delete_time" field.
func (eu *EmployersUpdate) SetDeleteTime(t time.Time) *EmployersUpdate {
	eu.mutation.SetDeleteTime(t)
	return eu
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (eu *EmployersUpdate) SetNillableDeleteTime(t *time.Time) *EmployersUpdate {
	if t != nil {
		eu.SetDeleteTime(*t)
	}
	return eu
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (eu *EmployersUpdate) ClearDeleteTime() *EmployersUpdate {
	eu.mutation.ClearDeleteTime()
	return eu
}

// SetNosap sets the "nosap" field.
func (eu *EmployersUpdate) SetNosap(s string) *EmployersUpdate {
	eu.mutation.SetNosap(s)
	return eu
}

// SetNillableNosap sets the "nosap" field if the given value is not nil.
func (eu *EmployersUpdate) SetNillableNosap(s *string) *EmployersUpdate {
	if s != nil {
		eu.SetNosap(*s)
	}
	return eu
}

// SetNip sets the "nip" field.
func (eu *EmployersUpdate) SetNip(s string) *EmployersUpdate {
	eu.mutation.SetNip(s)
	return eu
}

// SetNillableNip sets the "nip" field if the given value is not nil.
func (eu *EmployersUpdate) SetNillableNip(s *string) *EmployersUpdate {
	if s != nil {
		eu.SetNip(*s)
	}
	return eu
}

// SetKaryacode sets the "karyacode" field.
func (eu *EmployersUpdate) SetKaryacode(s string) *EmployersUpdate {
	eu.mutation.SetKaryacode(s)
	return eu
}

// SetNillableKaryacode sets the "karyacode" field if the given value is not nil.
func (eu *EmployersUpdate) SetNillableKaryacode(s *string) *EmployersUpdate {
	if s != nil {
		eu.SetKaryacode(*s)
	}
	return eu
}

// SetKaryaname sets the "karyaname" field.
func (eu *EmployersUpdate) SetKaryaname(s string) *EmployersUpdate {
	eu.mutation.SetKaryaname(s)
	return eu
}

// SetNillableKaryaname sets the "karyaname" field if the given value is not nil.
func (eu *EmployersUpdate) SetNillableKaryaname(s *string) *EmployersUpdate {
	if s != nil {
		eu.SetKaryaname(*s)
	}
	return eu
}

// SetDispName sets the "disp_name" field.
func (eu *EmployersUpdate) SetDispName(s string) *EmployersUpdate {
	eu.mutation.SetDispName(s)
	return eu
}

// SetNillableDispName sets the "disp_name" field if the given value is not nil.
func (eu *EmployersUpdate) SetNillableDispName(s *string) *EmployersUpdate {
	if s != nil {
		eu.SetDispName(*s)
	}
	return eu
}

// SetPassMesin sets the "pass_mesin" field.
func (eu *EmployersUpdate) SetPassMesin(s string) *EmployersUpdate {
	eu.mutation.SetPassMesin(s)
	return eu
}

// SetNillablePassMesin sets the "pass_mesin" field if the given value is not nil.
func (eu *EmployersUpdate) SetNillablePassMesin(s *string) *EmployersUpdate {
	if s != nil {
		eu.SetPassMesin(*s)
	}
	return eu
}

// SetRfidCard sets the "rfid_card" field.
func (eu *EmployersUpdate) SetRfidCard(s string) *EmployersUpdate {
	eu.mutation.SetRfidCard(s)
	return eu
}

// SetNillableRfidCard sets the "rfid_card" field if the given value is not nil.
func (eu *EmployersUpdate) SetNillableRfidCard(s *string) *EmployersUpdate {
	if s != nil {
		eu.SetRfidCard(*s)
	}
	return eu
}

// SetKodeFinger sets the "kode_finger" field.
func (eu *EmployersUpdate) SetKodeFinger(s string) *EmployersUpdate {
	eu.mutation.SetKodeFinger(s)
	return eu
}

// SetNillableKodeFinger sets the "kode_finger" field if the given value is not nil.
func (eu *EmployersUpdate) SetNillableKodeFinger(s *string) *EmployersUpdate {
	if s != nil {
		eu.SetKodeFinger(*s)
	}
	return eu
}

// SetDepartCode sets the "depart_code" field.
func (eu *EmployersUpdate) SetDepartCode(s string) *EmployersUpdate {
	eu.mutation.SetDepartCode(s)
	return eu
}

// SetNillableDepartCode sets the "depart_code" field if the given value is not nil.
func (eu *EmployersUpdate) SetNillableDepartCode(s *string) *EmployersUpdate {
	if s != nil {
		eu.SetDepartCode(*s)
	}
	return eu
}

// SetStatus sets the "status" field.
func (eu *EmployersUpdate) SetStatus(i int32) *EmployersUpdate {
	eu.mutation.ResetStatus()
	eu.mutation.SetStatus(i)
	return eu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (eu *EmployersUpdate) SetNillableStatus(i *int32) *EmployersUpdate {
	if i != nil {
		eu.SetStatus(*i)
	}
	return eu
}

// AddStatus adds i to the "status" field.
func (eu *EmployersUpdate) AddStatus(i int32) *EmployersUpdate {
	eu.mutation.AddStatus(i)
	return eu
}

// Mutation returns the EmployersMutation object of the builder.
func (eu *EmployersUpdate) Mutation() *EmployersMutation {
	return eu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (eu *EmployersUpdate) Save(ctx context.Context) (int, error) {
	eu.defaults()
	return withHooks(ctx, eu.sqlSave, eu.mutation, eu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (eu *EmployersUpdate) SaveX(ctx context.Context) int {
	affected, err := eu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (eu *EmployersUpdate) Exec(ctx context.Context) error {
	_, err := eu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eu *EmployersUpdate) ExecX(ctx context.Context) {
	if err := eu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (eu *EmployersUpdate) defaults() {
	if _, ok := eu.mutation.UpdateTime(); !ok {
		v := employers.UpdateDefaultUpdateTime()
		eu.mutation.SetUpdateTime(v)
	}
}

func (eu *EmployersUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(employers.Table, employers.Columns, sqlgraph.NewFieldSpec(employers.FieldID, field.TypeInt64))
	if ps := eu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := eu.mutation.UpdateTime(); ok {
		_spec.SetField(employers.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := eu.mutation.DeleteTime(); ok {
		_spec.SetField(employers.FieldDeleteTime, field.TypeTime, value)
	}
	if eu.mutation.DeleteTimeCleared() {
		_spec.ClearField(employers.FieldDeleteTime, field.TypeTime)
	}
	if value, ok := eu.mutation.Nosap(); ok {
		_spec.SetField(employers.FieldNosap, field.TypeString, value)
	}
	if value, ok := eu.mutation.Nip(); ok {
		_spec.SetField(employers.FieldNip, field.TypeString, value)
	}
	if value, ok := eu.mutation.Karyacode(); ok {
		_spec.SetField(employers.FieldKaryacode, field.TypeString, value)
	}
	if value, ok := eu.mutation.Karyaname(); ok {
		_spec.SetField(employers.FieldKaryaname, field.TypeString, value)
	}
	if value, ok := eu.mutation.DispName(); ok {
		_spec.SetField(employers.FieldDispName, field.TypeString, value)
	}
	if value, ok := eu.mutation.PassMesin(); ok {
		_spec.SetField(employers.FieldPassMesin, field.TypeString, value)
	}
	if value, ok := eu.mutation.RfidCard(); ok {
		_spec.SetField(employers.FieldRfidCard, field.TypeString, value)
	}
	if value, ok := eu.mutation.KodeFinger(); ok {
		_spec.SetField(employers.FieldKodeFinger, field.TypeString, value)
	}
	if value, ok := eu.mutation.DepartCode(); ok {
		_spec.SetField(employers.FieldDepartCode, field.TypeString, value)
	}
	if value, ok := eu.mutation.Status(); ok {
		_spec.SetField(employers.FieldStatus, field.TypeInt32, value)
	}
	if value, ok := eu.mutation.AddedStatus(); ok {
		_spec.AddField(employers.FieldStatus, field.TypeInt32, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, eu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{employers.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	eu.mutation.done = true
	return n, nil
}

// EmployersUpdateOne is the builder for updating a single Employers entity.
type EmployersUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EmployersMutation
}

// SetUpdateTime sets the "update_time" field.
func (euo *EmployersUpdateOne) SetUpdateTime(t time.Time) *EmployersUpdateOne {
	euo.mutation.SetUpdateTime(t)
	return euo
}

// SetDeleteTime sets the "delete_time" field.
func (euo *EmployersUpdateOne) SetDeleteTime(t time.Time) *EmployersUpdateOne {
	euo.mutation.SetDeleteTime(t)
	return euo
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (euo *EmployersUpdateOne) SetNillableDeleteTime(t *time.Time) *EmployersUpdateOne {
	if t != nil {
		euo.SetDeleteTime(*t)
	}
	return euo
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (euo *EmployersUpdateOne) ClearDeleteTime() *EmployersUpdateOne {
	euo.mutation.ClearDeleteTime()
	return euo
}

// SetNosap sets the "nosap" field.
func (euo *EmployersUpdateOne) SetNosap(s string) *EmployersUpdateOne {
	euo.mutation.SetNosap(s)
	return euo
}

// SetNillableNosap sets the "nosap" field if the given value is not nil.
func (euo *EmployersUpdateOne) SetNillableNosap(s *string) *EmployersUpdateOne {
	if s != nil {
		euo.SetNosap(*s)
	}
	return euo
}

// SetNip sets the "nip" field.
func (euo *EmployersUpdateOne) SetNip(s string) *EmployersUpdateOne {
	euo.mutation.SetNip(s)
	return euo
}

// SetNillableNip sets the "nip" field if the given value is not nil.
func (euo *EmployersUpdateOne) SetNillableNip(s *string) *EmployersUpdateOne {
	if s != nil {
		euo.SetNip(*s)
	}
	return euo
}

// SetKaryacode sets the "karyacode" field.
func (euo *EmployersUpdateOne) SetKaryacode(s string) *EmployersUpdateOne {
	euo.mutation.SetKaryacode(s)
	return euo
}

// SetNillableKaryacode sets the "karyacode" field if the given value is not nil.
func (euo *EmployersUpdateOne) SetNillableKaryacode(s *string) *EmployersUpdateOne {
	if s != nil {
		euo.SetKaryacode(*s)
	}
	return euo
}

// SetKaryaname sets the "karyaname" field.
func (euo *EmployersUpdateOne) SetKaryaname(s string) *EmployersUpdateOne {
	euo.mutation.SetKaryaname(s)
	return euo
}

// SetNillableKaryaname sets the "karyaname" field if the given value is not nil.
func (euo *EmployersUpdateOne) SetNillableKaryaname(s *string) *EmployersUpdateOne {
	if s != nil {
		euo.SetKaryaname(*s)
	}
	return euo
}

// SetDispName sets the "disp_name" field.
func (euo *EmployersUpdateOne) SetDispName(s string) *EmployersUpdateOne {
	euo.mutation.SetDispName(s)
	return euo
}

// SetNillableDispName sets the "disp_name" field if the given value is not nil.
func (euo *EmployersUpdateOne) SetNillableDispName(s *string) *EmployersUpdateOne {
	if s != nil {
		euo.SetDispName(*s)
	}
	return euo
}

// SetPassMesin sets the "pass_mesin" field.
func (euo *EmployersUpdateOne) SetPassMesin(s string) *EmployersUpdateOne {
	euo.mutation.SetPassMesin(s)
	return euo
}

// SetNillablePassMesin sets the "pass_mesin" field if the given value is not nil.
func (euo *EmployersUpdateOne) SetNillablePassMesin(s *string) *EmployersUpdateOne {
	if s != nil {
		euo.SetPassMesin(*s)
	}
	return euo
}

// SetRfidCard sets the "rfid_card" field.
func (euo *EmployersUpdateOne) SetRfidCard(s string) *EmployersUpdateOne {
	euo.mutation.SetRfidCard(s)
	return euo
}

// SetNillableRfidCard sets the "rfid_card" field if the given value is not nil.
func (euo *EmployersUpdateOne) SetNillableRfidCard(s *string) *EmployersUpdateOne {
	if s != nil {
		euo.SetRfidCard(*s)
	}
	return euo
}

// SetKodeFinger sets the "kode_finger" field.
func (euo *EmployersUpdateOne) SetKodeFinger(s string) *EmployersUpdateOne {
	euo.mutation.SetKodeFinger(s)
	return euo
}

// SetNillableKodeFinger sets the "kode_finger" field if the given value is not nil.
func (euo *EmployersUpdateOne) SetNillableKodeFinger(s *string) *EmployersUpdateOne {
	if s != nil {
		euo.SetKodeFinger(*s)
	}
	return euo
}

// SetDepartCode sets the "depart_code" field.
func (euo *EmployersUpdateOne) SetDepartCode(s string) *EmployersUpdateOne {
	euo.mutation.SetDepartCode(s)
	return euo
}

// SetNillableDepartCode sets the "depart_code" field if the given value is not nil.
func (euo *EmployersUpdateOne) SetNillableDepartCode(s *string) *EmployersUpdateOne {
	if s != nil {
		euo.SetDepartCode(*s)
	}
	return euo
}

// SetStatus sets the "status" field.
func (euo *EmployersUpdateOne) SetStatus(i int32) *EmployersUpdateOne {
	euo.mutation.ResetStatus()
	euo.mutation.SetStatus(i)
	return euo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (euo *EmployersUpdateOne) SetNillableStatus(i *int32) *EmployersUpdateOne {
	if i != nil {
		euo.SetStatus(*i)
	}
	return euo
}

// AddStatus adds i to the "status" field.
func (euo *EmployersUpdateOne) AddStatus(i int32) *EmployersUpdateOne {
	euo.mutation.AddStatus(i)
	return euo
}

// Mutation returns the EmployersMutation object of the builder.
func (euo *EmployersUpdateOne) Mutation() *EmployersMutation {
	return euo.mutation
}

// Where appends a list predicates to the EmployersUpdate builder.
func (euo *EmployersUpdateOne) Where(ps ...predicate.Employers) *EmployersUpdateOne {
	euo.mutation.Where(ps...)
	return euo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (euo *EmployersUpdateOne) Select(field string, fields ...string) *EmployersUpdateOne {
	euo.fields = append([]string{field}, fields...)
	return euo
}

// Save executes the query and returns the updated Employers entity.
func (euo *EmployersUpdateOne) Save(ctx context.Context) (*Employers, error) {
	euo.defaults()
	return withHooks(ctx, euo.sqlSave, euo.mutation, euo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (euo *EmployersUpdateOne) SaveX(ctx context.Context) *Employers {
	node, err := euo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (euo *EmployersUpdateOne) Exec(ctx context.Context) error {
	_, err := euo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (euo *EmployersUpdateOne) ExecX(ctx context.Context) {
	if err := euo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (euo *EmployersUpdateOne) defaults() {
	if _, ok := euo.mutation.UpdateTime(); !ok {
		v := employers.UpdateDefaultUpdateTime()
		euo.mutation.SetUpdateTime(v)
	}
}

func (euo *EmployersUpdateOne) sqlSave(ctx context.Context) (_node *Employers, err error) {
	_spec := sqlgraph.NewUpdateSpec(employers.Table, employers.Columns, sqlgraph.NewFieldSpec(employers.FieldID, field.TypeInt64))
	id, ok := euo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`model: missing "Employers.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := euo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, employers.FieldID)
		for _, f := range fields {
			if !employers.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("model: invalid field %q for query", f)}
			}
			if f != employers.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := euo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := euo.mutation.UpdateTime(); ok {
		_spec.SetField(employers.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := euo.mutation.DeleteTime(); ok {
		_spec.SetField(employers.FieldDeleteTime, field.TypeTime, value)
	}
	if euo.mutation.DeleteTimeCleared() {
		_spec.ClearField(employers.FieldDeleteTime, field.TypeTime)
	}
	if value, ok := euo.mutation.Nosap(); ok {
		_spec.SetField(employers.FieldNosap, field.TypeString, value)
	}
	if value, ok := euo.mutation.Nip(); ok {
		_spec.SetField(employers.FieldNip, field.TypeString, value)
	}
	if value, ok := euo.mutation.Karyacode(); ok {
		_spec.SetField(employers.FieldKaryacode, field.TypeString, value)
	}
	if value, ok := euo.mutation.Karyaname(); ok {
		_spec.SetField(employers.FieldKaryaname, field.TypeString, value)
	}
	if value, ok := euo.mutation.DispName(); ok {
		_spec.SetField(employers.FieldDispName, field.TypeString, value)
	}
	if value, ok := euo.mutation.PassMesin(); ok {
		_spec.SetField(employers.FieldPassMesin, field.TypeString, value)
	}
	if value, ok := euo.mutation.RfidCard(); ok {
		_spec.SetField(employers.FieldRfidCard, field.TypeString, value)
	}
	if value, ok := euo.mutation.KodeFinger(); ok {
		_spec.SetField(employers.FieldKodeFinger, field.TypeString, value)
	}
	if value, ok := euo.mutation.DepartCode(); ok {
		_spec.SetField(employers.FieldDepartCode, field.TypeString, value)
	}
	if value, ok := euo.mutation.Status(); ok {
		_spec.SetField(employers.FieldStatus, field.TypeInt32, value)
	}
	if value, ok := euo.mutation.AddedStatus(); ok {
		_spec.AddField(employers.FieldStatus, field.TypeInt32, value)
	}
	_node = &Employers{config: euo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, euo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{employers.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	euo.mutation.done = true
	return _node, nil
}
