// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/attendance/service/v1/attendace.proto
// Protobuf Java Version: 4.29.3

package attendace.service.v1;

public final class Attendace {
  private Attendace() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      Attendace.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AttendanceLogRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:attendace.service.v1.AttendanceLogRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 user_id = 1;</code>
     * @return The userId.
     */
    long getUserId();

    /**
     * <code>string device_ip = 2;</code>
     * @return The deviceIp.
     */
    java.lang.String getDeviceIp();
    /**
     * <code>string device_ip = 2;</code>
     * @return The bytes for deviceIp.
     */
    com.google.protobuf.ByteString
        getDeviceIpBytes();

    /**
     * <pre>
     * ISO8601 format
     * </pre>
     *
     * <code>string timestamp = 3;</code>
     * @return The timestamp.
     */
    java.lang.String getTimestamp();
    /**
     * <pre>
     * ISO8601 format
     * </pre>
     *
     * <code>string timestamp = 3;</code>
     * @return The bytes for timestamp.
     */
    com.google.protobuf.ByteString
        getTimestampBytes();

    /**
     * <pre>
     * 0 = clock_in, 1 = clock_out
     * </pre>
     *
     * <code>int32 status = 4;</code>
     * @return The status.
     */
    int getStatus();
  }
  /**
   * Protobuf type {@code attendace.service.v1.AttendanceLogRequest}
   */
  public static final class AttendanceLogRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:attendace.service.v1.AttendanceLogRequest)
      AttendanceLogRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        AttendanceLogRequest.class.getName());
    }
    // Use AttendanceLogRequest.newBuilder() to construct.
    private AttendanceLogRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private AttendanceLogRequest() {
      deviceIp_ = "";
      timestamp_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return attendace.service.v1.Attendace.internal_static_attendace_service_v1_AttendanceLogRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return attendace.service.v1.Attendace.internal_static_attendace_service_v1_AttendanceLogRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              attendace.service.v1.Attendace.AttendanceLogRequest.class, attendace.service.v1.Attendace.AttendanceLogRequest.Builder.class);
    }

    public static final int USER_ID_FIELD_NUMBER = 1;
    private long userId_ = 0L;
    /**
     * <code>int64 user_id = 1;</code>
     * @return The userId.
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }

    public static final int DEVICE_IP_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object deviceIp_ = "";
    /**
     * <code>string device_ip = 2;</code>
     * @return The deviceIp.
     */
    @java.lang.Override
    public java.lang.String getDeviceIp() {
      java.lang.Object ref = deviceIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceIp_ = s;
        return s;
      }
    }
    /**
     * <code>string device_ip = 2;</code>
     * @return The bytes for deviceIp.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDeviceIpBytes() {
      java.lang.Object ref = deviceIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object timestamp_ = "";
    /**
     * <pre>
     * ISO8601 format
     * </pre>
     *
     * <code>string timestamp = 3;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public java.lang.String getTimestamp() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timestamp_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * ISO8601 format
     * </pre>
     *
     * <code>string timestamp = 3;</code>
     * @return The bytes for timestamp.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTimestampBytes() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 4;
    private int status_ = 0;
    /**
     * <pre>
     * 0 = clock_in, 1 = clock_out
     * </pre>
     *
     * <code>int32 status = 4;</code>
     * @return The status.
     */
    @java.lang.Override
    public int getStatus() {
      return status_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != 0L) {
        output.writeInt64(1, userId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(deviceIp_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, deviceIp_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(timestamp_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, timestamp_);
      }
      if (status_ != 0) {
        output.writeInt32(4, status_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, userId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(deviceIp_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, deviceIp_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(timestamp_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, timestamp_);
      }
      if (status_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, status_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof attendace.service.v1.Attendace.AttendanceLogRequest)) {
        return super.equals(obj);
      }
      attendace.service.v1.Attendace.AttendanceLogRequest other = (attendace.service.v1.Attendace.AttendanceLogRequest) obj;

      if (getUserId()
          != other.getUserId()) return false;
      if (!getDeviceIp()
          .equals(other.getDeviceIp())) return false;
      if (!getTimestamp()
          .equals(other.getTimestamp())) return false;
      if (getStatus()
          != other.getStatus()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      hash = (37 * hash) + DEVICE_IP_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceIp().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static attendace.service.v1.Attendace.AttendanceLogRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static attendace.service.v1.Attendace.AttendanceLogRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static attendace.service.v1.Attendace.AttendanceLogRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static attendace.service.v1.Attendace.AttendanceLogRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static attendace.service.v1.Attendace.AttendanceLogRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static attendace.service.v1.Attendace.AttendanceLogRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static attendace.service.v1.Attendace.AttendanceLogRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static attendace.service.v1.Attendace.AttendanceLogRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static attendace.service.v1.Attendace.AttendanceLogRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static attendace.service.v1.Attendace.AttendanceLogRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static attendace.service.v1.Attendace.AttendanceLogRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static attendace.service.v1.Attendace.AttendanceLogRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(attendace.service.v1.Attendace.AttendanceLogRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code attendace.service.v1.AttendanceLogRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:attendace.service.v1.AttendanceLogRequest)
        attendace.service.v1.Attendace.AttendanceLogRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return attendace.service.v1.Attendace.internal_static_attendace_service_v1_AttendanceLogRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return attendace.service.v1.Attendace.internal_static_attendace_service_v1_AttendanceLogRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                attendace.service.v1.Attendace.AttendanceLogRequest.class, attendace.service.v1.Attendace.AttendanceLogRequest.Builder.class);
      }

      // Construct using attendace.service.v1.Attendace.AttendanceLogRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        userId_ = 0L;
        deviceIp_ = "";
        timestamp_ = "";
        status_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return attendace.service.v1.Attendace.internal_static_attendace_service_v1_AttendanceLogRequest_descriptor;
      }

      @java.lang.Override
      public attendace.service.v1.Attendace.AttendanceLogRequest getDefaultInstanceForType() {
        return attendace.service.v1.Attendace.AttendanceLogRequest.getDefaultInstance();
      }

      @java.lang.Override
      public attendace.service.v1.Attendace.AttendanceLogRequest build() {
        attendace.service.v1.Attendace.AttendanceLogRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public attendace.service.v1.Attendace.AttendanceLogRequest buildPartial() {
        attendace.service.v1.Attendace.AttendanceLogRequest result = new attendace.service.v1.Attendace.AttendanceLogRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(attendace.service.v1.Attendace.AttendanceLogRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.userId_ = userId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.deviceIp_ = deviceIp_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.timestamp_ = timestamp_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.status_ = status_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof attendace.service.v1.Attendace.AttendanceLogRequest) {
          return mergeFrom((attendace.service.v1.Attendace.AttendanceLogRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(attendace.service.v1.Attendace.AttendanceLogRequest other) {
        if (other == attendace.service.v1.Attendace.AttendanceLogRequest.getDefaultInstance()) return this;
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        if (!other.getDeviceIp().isEmpty()) {
          deviceIp_ = other.deviceIp_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getTimestamp().isEmpty()) {
          timestamp_ = other.timestamp_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.getStatus() != 0) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                userId_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                deviceIp_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                timestamp_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 32: {
                status_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long userId_ ;
      /**
       * <code>int64 user_id = 1;</code>
       * @return The userId.
       */
      @java.lang.Override
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>int64 user_id = 1;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(long value) {

        userId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 user_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object deviceIp_ = "";
      /**
       * <code>string device_ip = 2;</code>
       * @return The deviceIp.
       */
      public java.lang.String getDeviceIp() {
        java.lang.Object ref = deviceIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deviceIp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string device_ip = 2;</code>
       * @return The bytes for deviceIp.
       */
      public com.google.protobuf.ByteString
          getDeviceIpBytes() {
        java.lang.Object ref = deviceIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string device_ip = 2;</code>
       * @param value The deviceIp to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceIp(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        deviceIp_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string device_ip = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeviceIp() {
        deviceIp_ = getDefaultInstance().getDeviceIp();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string device_ip = 2;</code>
       * @param value The bytes for deviceIp to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        deviceIp_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object timestamp_ = "";
      /**
       * <pre>
       * ISO8601 format
       * </pre>
       *
       * <code>string timestamp = 3;</code>
       * @return The timestamp.
       */
      public java.lang.String getTimestamp() {
        java.lang.Object ref = timestamp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          timestamp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * ISO8601 format
       * </pre>
       *
       * <code>string timestamp = 3;</code>
       * @return The bytes for timestamp.
       */
      public com.google.protobuf.ByteString
          getTimestampBytes() {
        java.lang.Object ref = timestamp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timestamp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * ISO8601 format
       * </pre>
       *
       * <code>string timestamp = 3;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        timestamp_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ISO8601 format
       * </pre>
       *
       * <code>string timestamp = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        timestamp_ = getDefaultInstance().getTimestamp();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ISO8601 format
       * </pre>
       *
       * <code>string timestamp = 3;</code>
       * @param value The bytes for timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestampBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        timestamp_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private int status_ ;
      /**
       * <pre>
       * 0 = clock_in, 1 = clock_out
       * </pre>
       *
       * <code>int32 status = 4;</code>
       * @return The status.
       */
      @java.lang.Override
      public int getStatus() {
        return status_;
      }
      /**
       * <pre>
       * 0 = clock_in, 1 = clock_out
       * </pre>
       *
       * <code>int32 status = 4;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(int value) {

        status_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 0 = clock_in, 1 = clock_out
       * </pre>
       *
       * <code>int32 status = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000008);
        status_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:attendace.service.v1.AttendanceLogRequest)
    }

    // @@protoc_insertion_point(class_scope:attendace.service.v1.AttendanceLogRequest)
    private static final attendace.service.v1.Attendace.AttendanceLogRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new attendace.service.v1.Attendace.AttendanceLogRequest();
    }

    public static attendace.service.v1.Attendace.AttendanceLogRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AttendanceLogRequest>
        PARSER = new com.google.protobuf.AbstractParser<AttendanceLogRequest>() {
      @java.lang.Override
      public AttendanceLogRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<AttendanceLogRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AttendanceLogRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public attendace.service.v1.Attendace.AttendanceLogRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_attendace_service_v1_AttendanceLogRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_attendace_service_v1_AttendanceLogRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)api/attendance/service/v1/attendace.pr" +
      "oto\022\024attendace.service.v1\032\033google/protob" +
      "uf/empty.proto\"]\n\024AttendanceLogRequest\022\017" +
      "\n\007user_id\030\001 \001(\003\022\021\n\tdevice_ip\030\002 \001(\t\022\021\n\tti" +
      "mestamp\030\003 \001(\t\022\016\n\006status\030\004 \001(\0052o\n\021Attenda" +
      "nceService\022Z\n\024ReceiveAttendanceLog\022*.att" +
      "endace.service.v1.AttendanceLogRequest\032\026" +
      ".google.protobuf.EmptyB\035Z\033api/attendace/" +
      "service/v1;v1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_attendace_service_v1_AttendanceLogRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_attendace_service_v1_AttendanceLogRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_attendace_service_v1_AttendanceLogRequest_descriptor,
        new java.lang.String[] { "UserId", "DeviceIp", "Timestamp", "Status", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
